/** English observations, in the same topic/index order as the German catalogue. */
export const CITIZEN_LINES_EN_B = {
  recovery: [
    'First I will stand up, then I can think about the rest.',
    'My jacket certainly has a little more street experience now.',
    'I am checking both legs before I go anywhere.',
    'I need a moment before I start walking again.',
    'The ground was closer than I remembered it being.',
    'I am taking my time for the rest of the walk now.',
    'Oof. First, let me work out which way is up.',
    'I think I will stay close to ground level today.',
    'My dignity is taking longer to get up than I am.',
    'Right. Dust off the jacket and take a deep breath.',
    'I will skip that part of the walk from now on.',
    'I would rather not have an encore, thanks.',
    'Still got all my pockets? Good. Slowly onwards.',
    'That was a thoroughly unnecessary interruption.',
    'My knees have just filed a formal complaint.',
    'Let me see if my legs are back on speaking terms.',
    'The ground and I know each other far too well now.',
    'A quiet walk home would be lovely right now.',
    'I will tell this story later. With fewer hand gestures.',
    'I need a moment. Or a very good coffee.',
    'Get up slowly. Very, very slowly.',
    'I never want to change my perspective that quickly again.',
    'I had rather less excitement planned for today.',
    'At least my shoes are the right way up again.',
    'Well, that is my exercise done for the week.',
    'Just picking my thoughts up off the pavement.',
    'Next time, I am taking a completely different route.',
    'Phew. Let me check everything is back in place.',
    'I think a little break would be sensible now.',
    'This walk gets two stars from me today.',
  ],
  witness: [
    'I saw that happen, and it has really shaken me.',
    'Please give the people here a little space!',
    'I need to take a deep breath after seeing that.',
    'This is not how I imagined this walk would turn out.',
    'I had better stop here for a moment.',
    'I will still be thinking about that on the way home.',
    'Did you just see that too?',
    'Er, should somebody perhaps step in?',
    'You do not see that on every afternoon walk.',
    'I am fairly sure that is not how this is meant to work.',
    'You should be more careful with people!',
    'That really was not a good idea.',
    'Some very strange things are happening here today.',
    'A little less chaos right in front of me, please!',
    'I hope this still turns out all right.',
    'There are quieter ways to spend an afternoon.',
    'What on earth was that supposed to be?',
    'I am staying a few steps back, just in case.',
    'Maybe I should start wearing a helmet on my walks.',
    'I need a moment to find a mental filing cabinet for that.',
    'Our street has a few too many surprises today.',
    'I had absolutely no comment prepared for that scene.',
    'I can see it, but I still do not understand why.',
    'Could we go back to having a normal walk now?',
    'Hopefully this commotion will settle down soon.',
    'A quiet corner would suit me much better right now.',
  ],
  construction: [
    'My usual view is changing right in front of me.',
    'I am curious how this corner will look when it is finished.',
    'I may need to learn my familiar route all over again.',
    'The city is getting a new piece of everyday life here.',
    'I will come back for another look on my next walk.',
    'There is something new to discover here on every walk.',
    'Oh, something new is being built here.',
    'The neighbourhood is changing right before our eyes.',
    'I wonder what this will look like when it is finished.',
    'This corner looked completely different yesterday.',
    'Apparently our city does not take building breaks.',
    'A new little piece of the neighbourhood is growing here.',
    'Looks like I need to learn my way around again.',
    'I have rarely seen anything go up that quickly.',
    'Another building site for the map in my head.',
    'I wonder who will be living or working here soon.',
    'There is always something to watch at a building site.',
    'This corner is getting a whole new look.',
  ],
  demolition: [
    'It will take me a while to get used to the gap here.',
    'So the view I had yesterday is gone now.',
    'I wonder what will come next on this spot.',
    'A piece of my familiar route is disappearing there.',
    'I will probably keep referring to the old building for a while.',
    'Suddenly this corner is almost unrecognizable.',
    'That was still standing a moment ago!',
    'They are making a very thorough job of clearing space.',
    'Now you can see how much space that took up.',
    'Hopefully there is already a plan for the gap.',
    'I was not expecting that particular change.',
    'A familiar sight can disappear so quickly.',
    'I suppose I need a new landmark to navigate by.',
    'An empty plot. Let us see what becomes of it.',
    'There is suddenly a lot more sky around here.',
    'I am keeping my distance from the demolition.',
    'This new view will take some getting used to.',
    'Our city is having quite a reshuffle today.',
  ],
  park: [
    'Here I can let my thoughts move a little more slowly.',
    'I am keeping this park in mind for my next walk.',
    'I still have time for a lap through the greenery at lunch.',
    'This is a good place to leave my phone in my pocket.',
    'I would happily take the detour through the park again.',
    'A little greenery makes even a short walk more pleasant.',
    'A few minutes in the park would be perfect now.',
    'I always slow down a little when I pass here.',
    'A patch of green really does make a difference.',
    'This would be a good spot for my lunch break.',
    'I like routes that take me past a park.',
    'My thoughts get a little more room around here.',
    'Perhaps I will take another little loop through the greenery.',
    'Having a park nearby really is a luxury.',
    'The city feels a little softer around the edges here.',
    'This is a lovely place to catch your breath.',
    'Next time, I am bringing a book to the park.',
    'A little green between all these buildings feels good.',
    'This corner is worth the small detour.',
    'I would like to take a break here more often.',
    'My walk has just reached its best stretch.',
    'A free afternoon and this park. That would do nicely.',
  ],
  trees: [
    'These trees make the street feel a little less severe.',
    'I could try learning the tree species while I walk.',
    'A tree like that probably needs more patience than I do.',
    'I am remembering this row of trees as a landmark.',
    'It is worth looking up for a moment while walking here.',
    'I particularly like the path between these trees.',
    'The trees make this street so much more pleasant.',
    'I do enjoy a little rustling of leaves.',
    'Walking is simply nicer beneath the trees.',
    'I will gladly take the longer route for this row of trees.',
    'A few more green corners like this would be lovely.',
    'I should look up into the branches more often.',
    'The trees make the buildings look less stern.',
    'A tree never needs a diary. I rather envy that.',
    'At least this street has a leafy roof.',
    'Everything feels a little calmer between the trees.',
    'Counting leaves is certainly more relaxing than emails.',
    'I like this mixture of city streets and treetops.',
  ],
  water: [
    'I always lose track of the time a little by the water.',
    'I would rather stand a little back from the edge.',
    'I am happy to take a longer route for this view.',
    'My thoughts almost sort themselves out here by the water.',
    'I should show my friends the way down here sometime.',
    'I can still fit a few minutes by the shore into my day.',
    'I could linger by the water for a while.',
    'A little stroll along the bank would be nice now.',
    'Watching water is a surprisingly good way to do nothing.',
    'At last, somewhere to let my eyes wander.',
    'I especially like the path beside the water.',
    'I am still keeping both feet firmly on the bank.',
    'This would be a lovely place for a break.',
    'A good place to rinse out your thoughts. Figuratively.',
    'The city must have a lovely side seen from the water.',
    'I should make time for this view more often.',
    'I usually find better thoughts down by the water.',
    'Here, I would rather watch the water than my phone.',
    'A stretch of water brings a little calm to the day.',
    'Sadly, these shoes are not suitable for swimming.',
  ],
  pets: [
    'Someone seems to have their own idea of how this walk should go.',
    'I should explore my surroundings with that much curiosity.',
    'I will give our little neighbor a bit of space.',
    'Apparently this corner interests animals just as much as people.',
    'Some companions need to take breaks on their own schedule.',
    'I think every interesting trail is being investigated here.',
    'Oh, a little four-legged neighbour out for a wander.',
    'That one is probably having the more interesting walk.',
    'Those little paws are rather adorable.',
    'I will give the little one a bit of space.',
    'There is someone who probably knows this area better than I do.',
    'A furry neighbour makes the street a little friendlier.',
    'Hello, you! Out on your daily rounds too?',
    'Our little neighbour clearly has a plan of its own.',
    'That nose is giving the area a very thorough inspection.',
    'One glimpse of four little paws and my mood improves.',
    'Apparently no shoes are needed for this little outing.',
    'I am just looking. There is no need to reach out and touch.',
    'That furry little explorer seems to have a busy day ahead.',
    'Someone is much closer to all the interesting smells.',
    'A fellow walker with paws. Nice to have company.',
    'At least the little one takes time over every corner.',
  ],
  wildlife: [
    'I will stay quiet and watch from a distance.',
    'For a moment, that animal has my complete attention.',
    'Sometimes you come across a little nature right in the city.',
    'I do not want to startle that animal.',
    'I will take a little detour around our wild neighbor.',
    'I was not expecting this encounter along the way.',
    'Something is moving among the greenery.',
    'Look, an animal out there. Nice and calm now.',
    'I will watch from here and leave it in peace.',
    'Sometimes it is worth standing still for a moment.',
    'Out here, I suppose we are just visiting.',
    'That animal has probably noticed me already.',
    'A little wilderness belongs around here too.',
    'I will take the long way round to give it some space.',
    'An encounter like that makes an outing special.',
    'Watching quietly is probably the best idea here.',
    'The city ends, but life just carries on.',
    'Good to see there is still room for animals here.',
    'I will keep my distance. This is its territory, after all.',
    'That was a lovely little moment beside the path.',
  ],
  night: [
    'At this hour, I am already thinking about breakfast again.',
    'My bed is making a very convincing case against this walk.',
    'Night turns this familiar route into a different place.',
    'Tomorrow I will probably wonder why I was still out.',
    'One late lap is enough for me, then I am heading home.',
    'At this hour, you pay more attention to your own footsteps.',
    'The city sounds different at night somehow.',
    'One more evening lap, then I am heading home.',
    'I should not let my bedtime drift too far.',
    'Even my thoughts get quieter at this hour.',
    'The night has a street map all of its own.',
    'A short walk before bed does me good.',
    'I will feel this late outing tomorrow morning.',
    'I like the city at this late hour too.',
    'My bed is starting to sound like a good destination.',
    'Every familiar corner looks a little different at night.',
    'Just to the next corner. Then home, honestly.',
    'My body clock would quite like to clock off.',
    'Apparently even a late hour cannot settle this city down.',
    'An evening walk can so easily become a little detour.',
    'That is enough adventure for today. Time to head home.',
    'There is something special about the night air.',
  ],
} as const;
