/** English observations in the same topic and line order as the German originals. */
export const CITIZEN_LINES_EN_C = {
  lightsOn: [
    'Now I can recognize that corner again.',
    'The lighting is really helping me find my way just now.',
    'The walk home looks familiar again straight away.',
    'Now I do not have to study every step quite so carefully.',
    'The light changes the whole impression of this street.',
    'With the lighting on, I feel much more relaxed walking here.',
    'Ah, the lights are back on.',
    'Now I can see a bit more of the neighborhood.',
    'That light makes this corner feel much friendlier.',
    'The city just opened its eyes again.',
    'The walk home is nicer with the lights on.',
    'There, this feels a little cozier again.',
    'Someone found the right switch.',
    'A little light changes the whole mood.',
    'Now I can see where to go again.',
    'Well, that looks completely different.',
    'The lighting really suits this street.',
    'Bright enough to keep walking. Very handy.',
  ],
  lightsOff: [
    'A moment ago I could see much more clearly over there.',
    'I will wait a moment for my eyes to adjust.',
    'Without that light, this corner suddenly feels very different.',
    'I had better pay closer attention while walking now.',
    'The lighting here seems to have finished work for the day.',
    'I will take slightly shorter steps, just to be safe.',
    'Oh, the lights just went out.',
    'Someone must have flipped the switch.',
    'Everything suddenly looks quite different.',
    'Good thing I already know the way.',
    'Lights out, and the whole mood changes.',
    'Better watch where I put my feet now.',
    'The city seems quieter without the lights.',
    'My eyes need a moment to adjust.',
    'Was that the giant light switch?',
    'A few glowing landmarks have gone missing.',
    'The light is gone. Sadly, my walk home is not.',
    'One moment, same street. Next moment, different scenery.',
  ],
  rain: [
    'My jacket can handle more than I gave it credit for.',
    'Today the shortest route wins over the prettiest one.',
    'Of course my umbrella is in my other bag.',
    'My hair has plans of its own for this weather.',
    'A dry pair of socks would be a good start when I get home.',
    'I am walking a little more carefully on this wet ground.',
    'Of course my umbrella is nice and dry at home.',
    'I am giving that puddle a very wide berth.',
    'The rain clearly missed the walk on my calendar.',
    'My jacket is doing its absolute best.',
    'The city always smells a little different after rain.',
    'I should have worn my waterproof shoes.',
    'Somewhere with a roof would make a great destination.',
    'The sky is being very thorough with the watering.',
    'I will just pretend this was intentional.',
    'Wet socks were not on my schedule today.',
    'Happy for the plants. Less happy for my shoes.',
    'That next puddle looks deeper than it has any right to.',
    'A hot cup of tea just became much more tempting.',
    'This rain could really use a break.',
    'Onward, with as little splashing as possible.',
    'The weather just canceled my plans for my hair.',
  ],
  sun: [
    'In this weather, I am happy to take the longer way.',
    'I should have put my sunglasses in my pocket after all.',
    'My lunch break could do with being longer today.',
    'A glass of water would be a good idea before I go any farther.',
    'It does not take much to persuade me to go for a walk just now.',
    'Weather like this makes the front door rather more inviting.',
    'Even the long way round feels right today.',
    'The sunshine makes this walk feel like a little vacation.',
    'Glad I decided to get outside for a walk.',
    'A bright day like this lifts the mood right away.',
    'My sunglasses are probably next to my umbrella.',
    'I could really use a bit of sunshine today.',
    'This is definitely weather for a longer walk.',
    'The city looks fresher in this light.',
    'Better enjoy the sunshine while it lasts.',
    'A free spot in the shade would be nice later, too.',
    'I would happily take a few more hours of this today.',
    'The sun just made my walk home longer.',
  ],
  powerOutage: [
    'I hope the power supply gets going again soon.',
    'An outage can really disrupt the rhythm of the day.',
    'I wonder how long the fridge at home will stay cold.',
    'That will probably change a few plans for today.',
    'I hope my flashlight is where it is supposed to be.',
    'Reliability is what I want most from the power supply.',
    'Looks like the power is out around here.',
    'Hopefully the power supply will be steady again soon.',
    'You only realize how much needs electricity when it goes out.',
    'Someone should take a look at the power grid.',
    'A reliable power connection would really help here.',
    'Something is not quite right with the power supply.',
    'Hopefully they can get the power hooked up again soon.',
    'This corner seems to need a little help from the power grid.',
    'Electricity is one of those things you miss when it is gone.',
    'This looks like a power supply problem.',
    'A more reliable power supply would be nice.',
    'Hopefully this power problem is only temporary.',
  ],
  services: [
    'It is good to know where the public facilities are.',
    'I should remember this address in case I ever need it.',
    'Places like this remind you what keeps a city running.',
    'I hope the people working here have a quiet shift today.',
    'Getting to essential facilities should be easy for everyone.',
    "This is more than a building; it is part of the city's daily life.",
    'Good to have essential services close by.',
    'A city needs more than just houses.',
    'The work they do here helps all of us.',
    'Having places like this a short walk away is really handy.',
    'Glad there is room for essential services here.',
    'Easy to forget how much it takes to keep a city running.',
    'We all benefit from places like these every day.',
    'Good to see public services getting some attention, too.',
    'Useful work is part of the neighborhood here.',
    'A working city needs places like this.',
    'It is reassuring to have this nearby.',
    'A street does more for us than you might notice at first.',
  ],
  fire: [
    'I would rather not go any closer to this.',
    'The fire service needs the routes here kept as clear as possible.',
    'Please keep the entrance to the building clear!',
    'I hope everyone gets out of the danger area in time.',
    'I would rather continue my walk in another direction.',
    'Someone with the right equipment needs to deal with that quickly.',
    'There is a fire! Better back away quickly!',
    'Please stay back. That looks dangerous!',
    'Hopefully the firefighters will get here in time.',
    'Keep the access road clear for the fire trucks!',
    'Smoke up ahead. I am heading the other way.',
    'Away from the fire! This is no place to stand and watch!',
    'Has everyone moved away from the fire?',
    'A fire like that is really frightening.',
    'I am keeping well away from the flames.',
    'Watch out! Something is on fire up ahead!',
    'This is a job for the fire department.',
    'Keep moving, and leave the way clear!',
    'I hope everyone has noticed the fire.',
    'I am avoiding that corner until the fire is out.',
    'Nobody should be getting any closer.',
    'Better a long detour than walking right past the fire.',
  ],
  industry: [
    'Here you notice that work and production are part of the city too.',
    'I will probably look in another area for my next home.',
    'I would rather head back toward some greenery on this walk.',
    'I would welcome a bit more distance from the residential area.',
    'Jobs matter, but so does clean air in everyday life.',
    'I hope the neighbors are being considered here too.',
    'You can tell the city has work to do around here.',
    'The factories really define this part of town.',
    'I will find somewhere greener for my next walk.',
    'A good part of what we need must be made here.',
    'Homes and industry need a sensible distance between them.',
    'This neighborhood definitely sounds like work.',
    'A few strips of greenery would fit nicely here.',
    'Time to head back toward the residential streets.',
    'This is what the productive side of our city looks like.',
    'All these industrial buildings make me feel rather small.',
    'This part of town is more practical than cozy.',
    'A big park would make a nice balance to all this.',
    'Industry belongs in a city. So does a little breathing room.',
    'This corner is more of a workplace than a walking spot.',
  ],
  stadium: [
    'I could ask my friends about going to a game together.',
    'From here I can certainly explain the way home easily.',
    'For now, this walk is my exercise program for today.',
    'Next time I might bring a little more enthusiasm for sport.',
    "A stadium can take up quite a place in a city's story.",
    'I would be more interested in watching than playing.',
    'Even a stroll feels sporty next to the stadium.',
    'I would like to watch a game here someday.',
    'I would be exhausted after the warm-up lap.',
    'A stadium this size makes a pretty good landmark.',
    'Today my stamina only gets me as far as the sidelines.',
    'Maybe I can talk someone into coming to the next game.',
    'This place makes me want an afternoon of sports.',
    'I would probably last longer in the stands.',
    'By now, everyone here probably knows the stadium.',
    'I could get some exercise again. Could.',
    'Going to a game would be a good weekend plan.',
    'Around here, my walk almost counts as training.',
  ],
  airport: [
    'My suitcase has been sitting unused in the cupboard for months.',
    'I really could start planning another trip sometime.',
    'This place immediately reminds me of my last arrival home.',
    'For today, a trip as far as the next street will do.',
    'All I really need before traveling is an empty calendar.',
    'Perhaps this wanderlust will turn into a booking someday.',
    'Being near an airport always makes me want to travel.',
    'Other people are going away. I am just going for a walk.',
    'Maybe my next outing should involve a ticket.',
    'Plenty of big adventures must start right here.',
    'No suitcase with me, just a little wanderlust.',
    'An airport connects our city to so much of the world.',
    'A vacation would be nice. For now, a walk will do.',
    'I like the thought of setting off somewhere from here.',
    'Glad I have no departure time to remember today.',
    'Airports always get me thinking about long journeys.',
    'My boarding pass today is a pair of comfortable shoes.',
    'The world seems a little closer from here.',
  ],
} as const;
