/** English observations in the same order as their German counterparts. */
export const CITIZEN_LINES_EN_A = {
  everyday: [
    'I only meant to step outside. Now I am off on another adventure.',
    'First, coffee. Then we will see.',
    'Did I lock the front door? Surely I did. Right?',
    'I think I will take the long way today.',
    'Of course my shopping list is still on the table.',
    'Fresh bread is worth a little detour.',
    'My daily steps are practically taking care of themselves.',
    'The right turn must be around here somewhere.',
    'I was supposed to spend less time staring at my phone.',
    'A walk really helps put my thoughts in order.',
    'I am cooking tonight. I said that yesterday too.',
    'If I turn around now, I can still be on time.',
    'These shoes were more comfortable in the store.',
    'I think I know someone here. Or at least their jacket.',
    'A free afternoon would be perfect right now.',
    'Where was I going again? Oh, right.',
    'I have had the same song stuck in my head for three days.',
    'My fridge is empty, but my calendar is full.',
    'Just wandering through town with nowhere to be.',
    'Maybe I should start carrying a book again.',
    'My coffee at home is doing an excellent job of going cold.',
    'Today I am making time for the little things.',
    'One more lap, then I really am going home.',
    'I desperately need a jacket with more pockets.',
    'How have I managed to lose my keys again?',
    'I just had an idea. Hopefully it sticks around.',
    'Luckily, I have nothing heavy to carry today.',
    'This route looks a little different every time.',
    'I should really return that bowl to my neighbor.',
    'A proper breakfast would have made this trip easier.',
    'At least my step counter is happy today.',
    'I wonder if I have time for a small detour.',
    'Tomorrow I will start earlier. That sounds like a plan.',
    'I know a shortcut. Most of the time, anyway.',
    'Getting some fresh air was a good call.',
    'Sometimes all it takes is stepping outside.',
    'I really should have brought my reusable bag.',
    'Right, clear my head and then carry on.',
    'Pasta for dinner. At least that much is settled.',
    'I really need to start writing things down right away.',
  ],
  happy: [
    'I really feel at home here now.',
    'Our city is coming along. You notice it on a walk.',
    'I am just in a good mood today.',
    'I would hate to live anywhere else right now.',
    'I could get used to ordinary days like this.',
    'I like the way this neighborhood is growing.',
    'You can really feel comfortable here.',
    'Maybe I will invite some friends over this weekend.',
    'I even know a few of the neighbors now.',
    'This feels like a good place to call home.',
    'A lot of things are heading in the right direction.',
    'This city is really starting to grow on me.',
  ],
  unhappy: [
    'This neighborhood could use a little more attention.',
    'There is still plenty of room for improvement here.',
    'I hope someone hears our concerns eventually.',
    'Surely living here should feel a little easier.',
    'The city could really make daily life easier for us.',
    'It is the little problems that keep adding up here.',
    'I do not feel all that comfortable here right now.',
    'Unfortunately, a nice walk cannot fix everything.',
    'We could really use a proper plan around here.',
    'I wish life here would get a little better again.',
    'Our neighborhood deserves better than this.',
    'Hopefully those promises turn into something soon.',
  ],
  traffic: [
    'There is plenty of traffic rolling past today.',
    'I think I will stick to the sidewalk.',
    'You do not need a steering wheel to enjoy watching cars.',
    'I had better look twice at the next corner.',
    'At least walking does not require a parking space.',
    'Traffic has a rhythm all its own.',
    'Here comes the next car already.',
    'A little distance from the road never hurts.',
    'I will wait until the road is properly clear.',
    'Good thing I am on foot today.',
    'There is a lot happening on the road.',
    'You had better keep your eyes open around here.',
    'Everyone has somewhere to go. Me too, just more slowly.',
    'A quiet side street would be nice right about now.',
    'I will let that car go past first.',
    'Well, I suppose we are all heading in different directions.',
  ],
  fastCar: [
    'Do they have an appointment with the sound barrier?',
    'This street is far too narrow for that kind of speed.',
    'A little less gas would do just fine here.',
    'This is a city, not a racetrack!',
    'That car was gone before I could even look.',
    'I hope those brakes can keep up with that speed.',
    'I am taking another step back, just in case.',
    'Surely the grocery shopping cannot be that urgent.',
    'They drive like their coffee is trying to escape.',
    'At that speed, I am staying well out of the way.',
    'A little consideration takes less time than a repair.',
    'Whoa, that was seriously quick.',
    'Who glued their foot to the gas pedal?',
    'Slow down! People are walking here!',
    'That slipstream nearly blew my thoughts away.',
    'I hope that only saves time on paper.',
  ],
  drift: [
    'You can hear those tires squealing a street away.',
    'Sideways is an unusual direction to drive.',
    'That turn had far more drama than it needed.',
    'More handbrake than good judgment, that one.',
    'I would give those tires a little break now.',
    'Graceful? Maybe. Appropriate here? Not really.',
    'The back of that car wanted to reach the corner first.',
    'Please keep those stunts well away from me!',
    'That car is going sideways. I am going elsewhere.',
    'I will probably still hear that squealing tonight.',
    'That is how you wear out tires in record time.',
    'Surely that corner works without the sliding too.',
    'I do not usually expect cars to pull dance moves.',
    'The back end just chose a route of its own.',
    'I am staying behind the curb, just to be safe.',
    'Someone has just discovered the handbrake.',
  ],
  nearMiss: [
    'Whoa! That was definitely too close!',
    'My shoes do not need to meet your bumper!',
    'Any closer and we are swapping insurance details!',
    'I am standing here! On purpose, by the way!',
    'A little breathing room, please!',
    'My heart just went for a quick sprint.',
    'The sidewalk is meant for us too!',
    'Barely missing me is still far too close!',
    'I would like to get home on my own two feet!',
    'Hello? Eyes on the road!',
    'That was not a particularly friendly greeting!',
    'A little more personal space would be much nicer!',
    'Phew! I think I need a quick break.',
    'Please do not drive straight through my walk!',
    'Good grief, I only wanted to reach the next corner!',
    'I am not made of thin air!',
    'We really do not need to get to know each other that closely!',
    'That drive-by was far too personal!',
    'I saw you. Can you see me too?',
    'Deep breath. That only just turned out okay.',
  ],
  carCrash: [
    'Oh dear, that was quite a crash.',
    'That sounded like an expensive appointment.',
    'First, keep some distance and see what happened.',
    'Both cars apparently wanted the same spot.',
    'I hope nobody was hurt in that.',
    'One moment you are driving, the next you have a dent problem.',
    'They must have heard that bang at the next corner.',
    'I think I will stay well off the road here.',
    'Looks like those drivers have a few things to discuss.',
    'That gap was apparently smaller than expected.',
    'Keeping calm seems like the best plan now.',
    'Having a bumper does not mean you have to keep bumping things.',
    'That was an encounter with very little personal space.',
    'With all that confusion, I would rather hang back.',
    'Everyone slow down, please. Something just happened here.',
    'Ouch. That was much louder than a parking scrape.',
  ],
  personHit: [
    'Someone just got hit by a car!',
    'Stop! There is a person on the ground!',
    'Please give them space. They need help!',
    'Are you okay? Can you hear me?',
    'Do not drive off! Check on that person first!',
    'Oh no! I hope that was not too bad.',
    'Clear the road! Someone needs help here!',
    'That happened so fast. Please be careful now!',
    'Is there anyone here who can help?',
    'Watch out! Someone is in front of the car!',
    'We need to check whether that person is okay.',
    'Please do not crowd them. Leave some room!',
    'That was a person, not an obstacle!',
    'Stop and check on them, right now!',
    'I am staying until we know what happened.',
    'Hopefully they will be able to get up again soon.',
  ],
  held: [
    'Uh, my feet appear to be taking a break!',
    'Could you put me back on the ground?',
    'I did not book a flight today!',
    'This was not really part of my walking route.',
    'Hello up there! I am not a key chain!',
    'Careful with the jacket! It is still pretty new!',
    'My preferred cruising altitude is zero.',
    'Is this the new public transit system?',
    'I would like to keep my shoes on the ground.',
    'We could also just talk to each other!',
    'This is a very unexpected shortcut!',
    'No spin cycle, please!',
    'I wanted fresh air, but not from every direction!',
    'A sightseeing flight was not on my shopping list!',
    'The view is good. The rest is debatable.',
    'I prefer elevators with walls and buttons!',
    'You do know I am not a game piece? Right?',
    'Nice and slow. I am fond of my joints.',
    'Ground beneath my feet would be my first choice right now!',
    'I wanted to go home, not up into the clouds!',
    'This is an exceptionally direct way to introduce yourself.',
    'Could I please decide where I am going again?',
    'It is hard to hold on when someone is holding you!',
    'My fear of heights was supposed to have today off.',
  ],
  thrown: [
    'This is considerably faster than my walking pace!',
    'I am not built for flight paths like this!',
    'Ground, please approach me slowly!',
    'Who replaced the bus timetable with a launch schedule?',
    'I am missing a very important safety harness here!',
    'That was definitely not a gentle set-down!',
    'I take it all back! Except my fear of heights!',
    'This is not how I pictured putting a spring in my step!',
    'My pockets were not designed for aerobatics!',
    'I would like to end this excursion early!',
    'Could someone pause gravity for a moment?',
    'My route home just took a very strange turn!',
    'Do not throw me! That is not part of going for a walk!',
    'I am neither a ball nor a paper airplane!',
    'Okay, that was far too much momentum!',
    'The landing worries me more than the takeoff!',
    'A handrail would be extremely useful right now!',
    'I am definitely wearing the wrong shoes for this route!',
    'My knees would like a word with the tour operator!',
    'Please skip the acceleration next time!',
  ],
} as const;
