import { getLocale } from './i18n';
import { CITIZEN_LINES_EN_A } from './citizen-dialogue-en-a';
import { CITIZEN_LINES_EN_B } from './citizen-dialogue-en-b';
import { CITIZEN_LINES_EN_C } from './citizen-dialogue-en-c';

/** Authored observations: callers select a topic only after observing its cause. */
export const CITIZEN_LINES = {
  everyday: [
    'Ich wollte nur kurz raus. Jetzt bin ich schon wieder unterwegs.',
    'Erst ein Kaffee, dann sehen wir weiter.',
    'Habe ich die Haustür abgeschlossen? Bestimmt. Oder?',
    'Ich gehe heute mal den längeren Weg.',
    'Die Einkaufsliste liegt natürlich noch auf dem Tisch.',
    'Für frische Brötchen nehme ich den Umweg gern in Kauf.',
    'Meine Schritte zählen sich heute praktisch von allein.',
    'Irgendwo hier müsste die richtige Abzweigung sein.',
    'Ich wollte eigentlich weniger aufs Handy schauen.',
    'Ein Spaziergang sortiert die Gedanken ganz gut.',
    'Heute koche ich. Das habe ich gestern auch gesagt.',
    'Wenn ich jetzt umdrehe, bin ich noch pünktlich.',
    'Diese Schuhe waren im Laden bequemer.',
    'Ich glaube, ich kenne hier jemanden. Oder dessen Jacke.',
    'Ein freier Nachmittag wäre jetzt genau richtig.',
    'Wo wollte ich noch gleich hin? Ach ja.',
    'Ich habe seit drei Tagen einen Ohrwurm.',
    'Der Kühlschrank ist leer, aber mein Kalender voll.',
    'Einfach mal ohne Ziel durch die Stadt laufen.',
    'Vielleicht sollte ich wieder ein Buch mitnehmen.',
    'Mein Kaffee zu Hause wird gerade hervorragend kalt.',
    'Heute nehme ich mir Zeit für die kleinen Dinge.',
    'Noch eine Runde, dann geht es wirklich nach Hause.',
    'Ich brauche dringend eine Jacke mit mehr Taschen.',
    'Wie kann man denn schon wieder die Schlüssel verlegen?',
    'Ich habe gerade eine Idee. Hoffentlich bleibt sie.',
    'Zum Glück muss ich heute nichts Schweres tragen.',
    'Der Weg kommt mir jedes Mal ein bisschen anders vor.',
    'Ich sollte meiner Nachbarin die Schüssel zurückbringen.',
    'Ein gutes Frühstück hätte diese Reise einfacher gemacht.',
    'Mein Schrittzähler ist heute jedenfalls zufrieden.',
    'Ob ich noch Zeit für einen kleinen Umweg habe?',
    'Morgen fange ich früher an. Das klingt nach einem Plan.',
    'Ich kenne eine Abkürzung. Meistens jedenfalls.',
    'Ein bisschen frische Luft war eine gute Entscheidung.',
    'Manchmal reicht es, einfach vor die Tür zu gehen.',
    'Ich hätte die Stofftasche doch mitnehmen sollen.',
    'So, einmal den Kopf lüften und dann weiter.',
    'Nachher gibt es Nudeln. Das steht immerhin schon fest.',
    'Ich muss mir Dinge wirklich mal sofort aufschreiben.',
  ],
  happy: [
    'Hier bin ich inzwischen richtig zu Hause.',
    'Unsere Stadt macht sich. Das merkt man beim Spazieren.',
    'Heute habe ich einfach gute Laune.',
    'Ich würde gerade ungern woanders wohnen.',
    'So kann ein ganz normaler Tag ruhig öfter sein.',
    'Ich mag es, wie sich dieses Viertel entwickelt.',
    'Man kann sich hier wirklich wohlfühlen.',
    'Vielleicht lade ich am Wochenende Freunde hierher ein.',
    'Ich kenne inzwischen sogar ein paar Nachbarn.',
    'Das hier fühlt sich nach einem guten Zuhause an.',
    'Es läuft gerade vieles in die richtige Richtung.',
    'Die Stadt wächst mir langsam richtig ans Herz.',
  ],
  unhappy: [
    'Ein bisschen mehr Aufmerksamkeit täte dem Viertel gut.',
    'Hier gibt es noch genug zu verbessern.',
    'Ich hoffe, unsere Sorgen kommen irgendwann an.',
    'Wohnen sollte sich doch leichter anfühlen.',
    'Die Stadt könnte uns den Alltag wirklich einfacher machen.',
    'Es sind die kleinen Probleme, die sich hier summieren.',
    'So richtig wohl fühle ich mich im Moment nicht.',
    'Ein schöner Spaziergang löst leider nicht alles.',
    'Wir brauchen hier langsam mal einen guten Plan.',
    'Ich wünsche mir wieder mehr Lebensqualität.',
    'Unser Viertel hat mehr verdient als das.',
    'Hoffentlich wird aus den Versprechen bald etwas.',
  ],
  traffic: [
    'Hier rollt heute ordentlich was vorbei.',
    'Ich bleibe lieber auf dem Gehweg.',
    'Autos beobachten geht auch ohne eigenes Lenkrad.',
    'An der nächsten Ecke schaue ich lieber zweimal.',
    'Zu Fuß brauche ich wenigstens keinen Parkplatz.',
    'Der Verkehr hat seinen eigenen Rhythmus.',
    'Da kommt schon das nächste Auto.',
    'Ein kleiner Abstand zur Fahrbahn schadet nicht.',
    'Ich warte, bis die Straße wirklich frei ist.',
    'Zum Glück bin ich heute zu Fuß unterwegs.',
    'Ganz schön viel Bewegung auf der Straße.',
    'Hier sollte man seine Augen besser offen halten.',
    'Jeder will irgendwohin. Ich auch, nur langsamer.',
    'Eine ruhige Nebenstraße wäre jetzt angenehm.',
    'Ich lasse den Wagen erst mal vorbeifahren.',
    'Na, dann rollen wir wohl alle in verschiedene Richtungen.',
  ],
  fastCar: [
    'Hat der eine Verabredung mit der Schallmauer?',
    'Für die Geschwindigkeit ist mir die Straße zu schmal.',
    'Etwas weniger Gas würde hier völlig reichen.',
    'Das ist eine Stadt, keine Rennstrecke!',
    'Der war ja schon vorbei, bevor ich schauen konnte.',
    'Hoffentlich reichen die Bremsen zu dem Tempo.',
    'Ich mache vorsichtshalber noch einen Schritt zurück.',
    'So dringend kann der Einkauf doch nicht sein.',
    'Der fährt, als würde sein Kaffee davonlaufen.',
    'Bei dem Tempo bleibe ich schön am Rand.',
    'Ein bisschen Rücksicht wäre schneller erklärt als repariert.',
    'Uff, das war jetzt aber flott.',
    'Wer hat denn hier den Fuß aufs Gaspedal geklebt?',
    'Langsamer! Hier gehen Menschen zu Fuß!',
    'Der Fahrtwind hat mir fast die Gedanken weggeweht.',
    'Zeit spart man so hoffentlich nur auf dem Papier.',
  ],
  drift: [
    'Die Reifen quietschen ja bis zur nächsten Straße.',
    'Seitwärts ist eine ungewöhnliche Fahrtrichtung.',
    'Diese Kurve hatte deutlich mehr Drama als nötig.',
    'Das war wohl mehr Handbremse als gute Idee.',
    'Ich würde den Reifen jetzt eine Pause gönnen.',
    'Elegant? Vielleicht. Hier angebracht? Eher nicht.',
    'Da wollte das Heck wohl zuerst um die Ecke.',
    'Bitte diese Kunststücke mit Abstand zu mir!',
    'Der Wagen fährt quer, und ich gehe lieber weiter.',
    'Ich höre das Quietschen vermutlich heute Abend noch.',
    'So verschleißt man Reifen in Rekordzeit.',
    'Die Kurve wäre doch auch ohne Rutschen zu schaffen.',
    'Mit so einem Tanzschritt rechne ich bei Autos nicht.',
    'Das Heck hat gerade eine eigene Route gewählt.',
    'Ich stehe sicherheitshalber hinter der Bordsteinkante.',
    'Da hat jemand die Handbremse für sich entdeckt.',
  ],
  nearMiss: [
    'Huch! Das war mir eindeutig zu nah!',
    'Meine Schuhe brauchen keinen Kontakt zur Stoßstange!',
    'Noch ein Stück näher und wir tauschen Versicherungen!',
    'Ich stehe hier! Mit Absicht übrigens!',
    'Ein bisschen Platz zum Atmen, bitte!',
    'Mein Herz hat gerade einen kleinen Sprint hingelegt.',
    'Der Gehweg gehört eigentlich auch uns!',
    'Knapp daneben ist immer noch viel zu knapp!',
    'Ich möchte meinen Heimweg bitte auf zwei Beinen beenden!',
    'Hallo? Augen auf die Straße!',
    'Das war kein besonders freundlicher Gruß!',
    'Eine Armlänge Abstand wäre mir deutlich lieber!',
    'Puh! Ich glaube, ich brauche kurz eine Pause.',
    'Bitte nicht durch meinen Spaziergang fahren!',
    'Meine Güte, ich wollte nur an die andere Ecke!',
    'Ich bin doch nicht aus Luft!',
    'So nah müssen wir uns wirklich nicht kennenlernen!',
    'Das war jetzt eine viel zu persönliche Vorbeifahrt!',
    'Ich habe dich gesehen. Siehst du mich auch?',
    'Einmal tief durchatmen. Das ging gerade noch gut.',
  ],
  carCrash: [
    'Oje, da hat es gerade ordentlich gekracht.',
    'Das Geräusch klang nach einem teuren Termin.',
    'Jetzt erst mal Abstand halten und schauen.',
    'Die beiden Autos wollten wohl denselben Platz.',
    'Hoffentlich ist da niemandem etwas passiert.',
    'So schnell wird aus einer Fahrt ein Blechproblem.',
    'Den Knall hat man bestimmt bis zur nächsten Ecke gehört.',
    'Ich bleibe hier lieber außerhalb der Fahrbahn.',
    'Das sieht nach Gesprächsbedarf zwischen den Fahrern aus.',
    'Da war die Lücke offenbar kleiner als gedacht.',
    'Jetzt ist Ruhe bewahren wohl der beste Plan.',
    'Eine Stoßstange heißt nicht, dass man ständig stoßen muss.',
    'Das war eine Begegnung mit sehr wenig Abstand.',
    'Bei dem Durcheinander halte ich mich lieber zurück.',
    'Bitte alle langsam, hier ist gerade etwas passiert.',
    'Autsch. Das war deutlich lauter als ein Parkrempler.',
  ],
  personHit: [
    'Da wurde gerade jemand angefahren!',
    'Halt an! Da liegt ein Mensch!',
    'Bitte Platz lassen, die Person braucht Hilfe!',
    'Alles in Ordnung? Kannst du mich hören?',
    'Nicht weiterfahren! Schau erst nach der Person!',
    'Oh nein! Ich hoffe, das war nicht zu heftig.',
    'Weg von der Straße, hier braucht jemand Hilfe!',
    'Das ging so schnell. Bitte jetzt vorsichtig!',
    'Ist jemand da, der helfen kann?',
    'Pass auf! Da ist jemand vor dem Auto!',
    'Wir müssen schauen, ob es der Person gut geht.',
    'Bitte nicht drängeln, lass etwas Platz!',
    'Das war ein Mensch, kein Hindernis!',
    'Anhalten und nachsehen, sofort!',
    'Ich bleibe hier, bis klar ist, was passiert ist.',
    'Hoffentlich kann die Person gleich wieder aufstehen.',
  ],
  held: [
    'Äh, meine Füße haben gerade frei!',
    'Könntest du mich wieder auf den Boden stellen?',
    'Ich hatte heute keinen Flug gebucht!',
    'So war der Spaziergang eigentlich nicht geplant.',
    'Hallo da oben! Ich bin kein Schlüsselanhänger!',
    'Vorsichtig mit der Jacke, die ist noch recht neu!',
    'Meine bevorzugte Reiseflughöhe ist null Meter.',
    'Ist das jetzt der neue öffentliche Nahverkehr?',
    'Ich würde gern mit den Schuhen unten bleiben.',
    'Wir können auch einfach miteinander reden!',
    'Das ist eine sehr überraschende Abkürzung!',
    'Bitte ohne Schleudergang, ja?',
    'Ich wollte frische Luft, aber nicht von allen Seiten!',
    'Meine Einkaufsliste enthielt keinen Rundflug!',
    'Die Aussicht ist gut. Der Rest ist diskutabel.',
    'Ich bevorzuge Aufzüge mit Wänden und Knöpfen!',
    'Du weißt schon, dass ich keine Spielfigur bin? Oder?',
    'Ganz langsam. Ich mag meine Gelenke.',
    'Boden unter den Füßen wäre jetzt mein Favorit!',
    'Ich wollte nach Hause und nicht in die Wolken!',
    'Das ist eine ausgesprochen direkte Kontaktaufnahme.',
    'Kann ich bitte wieder selbst entscheiden, wohin ich gehe?',
    'Festhalten ist schwierig, wenn man festgehalten wird!',
    'Meine Höhenangst hatte heute eigentlich Urlaub.',
  ],
  thrown: [
    'Das ist deutlich schneller als mein Schritttempo!',
    'Ich bin für solche Flugbahnen nicht gebaut!',
    'Boden, bitte komm mir langsam entgegen!',
    'Wer hat hier den Fahrplan gegen einen Wurfplan getauscht?',
    'Mir fehlt gerade eine sehr wichtige Sicherheitsleine!',
    'Das war definitiv kein sanftes Absetzen!',
    'Ich nehme alles zurück! Außer meine Höhenangst!',
    'So hatte ich mir Schwung im Alltag nicht vorgestellt!',
    'Meine Taschen sind nicht für Kunstflug gemacht!',
    'Ich würde diesen Ausflug gern vorzeitig beenden!',
    'Kann man die Schwerkraft kurz auf Pause stellen?',
    'Der Heimweg hat gerade eine seltsame Richtung bekommen!',
    'Nicht werfen! Das gehört nicht zum Spaziergang!',
    'Ich bin weder Ball noch Papierflieger!',
    'Okay, das war jetzt zu viel Schwung!',
    'Die Landung macht mir mehr Sorgen als der Start!',
    'Ein Geländer wäre gerade ausgesprochen praktisch!',
    'Ich habe für diese Strecke eindeutig die falschen Schuhe!',
    'Meine Knie möchten mit der Reiseleitung sprechen!',
    'Bitte das nächste Mal ohne Beschleunigung!',
  ],
  recovery: [
    'Uff. Erst mal wieder sortieren, wo oben ist.',
    'Ich glaube, ich bleibe heute lieber in Bodennähe.',
    'Meine Würde braucht länger zum Aufstehen als ich.',
    'So. Einmal die Jacke abklopfen und tief durchatmen.',
    'Diesen Teil des Spaziergangs lasse ich künftig aus.',
    'Ich möchte bitte keine Wiederholung davon.',
    'Alle Taschen noch da? Gut. Weiter langsam.',
    'Das war eine reichlich unnötige Unterbrechung.',
    'Meine Knie haben gerade eine Beschwerde eingereicht.',
    'Ich teste erst mal, ob die Beine wieder mitmachen.',
    'Der Boden und ich kennen uns jetzt zu gut.',
    'Ein ruhiger Heimweg wäre jetzt mein Wunsch.',
    'Das erzähle ich später. Mit etwas weniger Gestik.',
    'Ich brauche einen Moment. Oder einen sehr guten Kaffee.',
    'Langsam aufstehen. Ganz langsam.',
    'So schnell möchte ich die Perspektive nie wieder wechseln.',
    'Ich hatte mir für heute weniger Aufregung vorgenommen.',
    'Meine Schuhe stehen immerhin wieder richtig herum.',
    'Das war mein Sportprogramm für diese Woche.',
    'Ich sammle gerade meine Gedanken vom Boden auf.',
    'Nächstes Mal nehme ich einen wirklich anderen Weg.',
    'Puh. Erst mal schauen, ob alles wieder sitzt.',
    'Ich glaube, eine Pause wäre jetzt vernünftig.',
    'Der Spaziergang bekommt von mir heute nur zwei Sterne.',
  ],
  witness: [
    'Hast du das auch gerade gesehen?',
    'Äh, sollte man da vielleicht mal eingreifen?',
    'So etwas sieht man auch nicht bei jedem Spaziergang.',
    'Ich bin ziemlich sicher, dass das nicht so gehört.',
    'Mit Menschen geht man doch vorsichtiger um!',
    'Das war jetzt wirklich keine gute Idee.',
    'Hier passieren heute sehr merkwürdige Dinge.',
    'Bitte ein bisschen weniger Chaos vor meiner Nase!',
    'Ich hoffe, da geht alles noch gut aus.',
    'Man kann einen Nachmittag auch ruhiger verbringen.',
    'Was um alles in der Welt war denn das?',
    'Ich bleibe vorsichtshalber ein paar Schritte zurück.',
    'Demnächst gehe ich vielleicht mit einem Helm raus.',
    'Das muss ich erst mal in meinem Kopf einsortieren.',
    'Unsere Straße überrascht mich heute ein bisschen zu sehr.',
    'Für diese Szene hatte ich keinen Satz vorbereitet.',
    'Ich sehe es und verstehe trotzdem nicht, warum.',
    'Kann hier bitte wieder ein normaler Spaziergang stattfinden?',
    'Hoffentlich hört dieses Durcheinander gleich auf.',
    'Eine ruhige Ecke wäre mir jetzt deutlich lieber.',
  ],
  construction: [
    'Oh, hier wird gerade etwas Neues gebaut.',
    'Da verändert sich das Viertel direkt vor unseren Augen.',
    'Ich bin gespannt, wie es hier fertig aussieht.',
    'Gestern sah diese Ecke noch ganz anders aus.',
    'Unsere Stadt gönnt sich offenbar keine Baupause.',
    'Hier wächst gerade ein neues Stück Nachbarschaft.',
    'Da muss ich mir den Weg wohl neu merken.',
    'So schnell habe ich selten etwas entstehen sehen.',
    'Noch eine Baustelle für meine innere Stadtkarte.',
    'Mal sehen, wer hier bald einzieht oder arbeitet.',
    'Wenn gebaut wird, gibt es immer etwas zu beobachten.',
    'Diese Ecke bekommt gerade ein neues Gesicht.',
  ],
  demolition: [
    'Das stand doch eben noch da!',
    'Hier wird gerade ziemlich gründlich Platz gemacht.',
    'Jetzt sieht man erst, wie viel Fläche das war.',
    'Hoffentlich gibt es schon einen Plan für die Lücke.',
    'Mit dieser Veränderung habe ich nicht gerechnet.',
    'So schnell verschwindet ein vertrauter Anblick.',
    'Da muss ich meinen Orientierungspunkt wohl ersetzen.',
    'Eine freie Fläche. Mal sehen, was daraus wird.',
    'Hier ist jetzt auf einmal deutlich mehr Himmel.',
    'Ich halte lieber Abstand vom Abriss.',
    'An diese neue Aussicht muss ich mich erst gewöhnen.',
    'Unsere Stadt wird heute ordentlich umgeräumt.',
  ],
  park: [
    'Ein paar Minuten im Park wären jetzt perfekt.',
    'Hier gehe ich automatisch ein bisschen langsamer.',
    'So ein Stück Grün macht wirklich einen Unterschied.',
    'Das wäre ein guter Ort für meine Mittagspause.',
    'Ich mag Wege, die an einem Park vorbeiführen.',
    'Hier bekommt der Kopf etwas mehr Platz.',
    'Vielleicht drehe ich noch eine kleine Runde durchs Grün.',
    'Ein Park in der Nähe ist schon ein Luxus.',
    'Hier fühlt sich die Stadt gleich etwas weicher an.',
    'Das ist eine schöne Stelle zum Durchatmen.',
    'Nächstes Mal bringe ich ein Buch für den Park mit.',
    'Ein bisschen Grün zwischen all den Gebäuden tut gut.',
    'Für diese Ecke lohnt sich der kleine Umweg.',
    'Ich würde hier gern öfter eine Pause einlegen.',
    'Mein Spaziergang hat gerade seinen besten Abschnitt.',
    'Ein freier Nachmittag und dieser Park, das wäre was.',
  ],
  trees: [
    'Die Bäume machen die Straße gleich angenehmer.',
    'Ein bisschen Blätterrascheln höre ich gern.',
    'Unter Bäumen spaziert es sich einfach schöner.',
    'Für diese Baumreihe nehme ich gern den längeren Weg.',
    'Mehr solche grünen Ecken wären wirklich schön.',
    'Ich sollte öfter mal nach oben in die Zweige schauen.',
    'Die Bäume lassen die Häuser weniger streng aussehen.',
    'So ein Baum braucht keinen Terminkalender. Beneidenswert.',
    'Hier hat die Straße wenigstens ein grünes Dach.',
    'Zwischen den Bäumen fühlt sich alles etwas ruhiger an.',
    'Blätter zählen ist immerhin entspannter als E-Mails.',
    'Ich mag diese Mischung aus Stadt und Baumkronen.',
  ],
  water: [
    'Am Wasser könnte ich länger stehen bleiben.',
    'Eine kleine Runde am Ufer wäre jetzt schön.',
    'Wasser anschauen ist erstaunlich gutes Nichtstun.',
    'Hier bekommt der Blick endlich mal etwas Weite.',
    'Der Weg am Wasser gefällt mir besonders gut.',
    'Ich bleibe trotzdem mit beiden Füßen am Ufer.',
    'Das wäre ein schöner Platz für eine Pause.',
    'Hier lässt sich der Kopf gut freispülen. Bildlich.',
    'Die Stadt hat vom Wasser aus bestimmt eine schöne Seite.',
    'Ich sollte mir öfter Zeit für diesen Ausblick nehmen.',
    'Am Ufer komme ich meistens auf bessere Gedanken.',
    'Hier schaue ich lieber aufs Wasser als aufs Handy.',
    'So eine Wasserfläche bringt Ruhe in den Tag.',
    'Zum Schwimmen sind meine Schuhe leider ungeeignet.',
  ],
  pets: [
    'Oh, da ist ja ein kleiner Vierbeiner unterwegs.',
    'Der hat vermutlich den spannenderen Spaziergang.',
    'Diese kleinen Pfoten sind schon ziemlich niedlich.',
    'Ich lasse dem Tierchen lieber ein bisschen Platz.',
    'Da kennt jemand das Viertel wahrscheinlich besser als ich.',
    'So ein tierischer Nachbar macht die Straße gleich netter.',
    'Hallo, du! Auch auf deiner täglichen Runde?',
    'Der kleine Mitbewohner hat offenbar einen eigenen Plan.',
    'Da wird die Gegend mit sehr gründlicher Nase erkundet.',
    'Ein Blick auf vier Pfoten, und meine Laune ist besser.',
    'Für den kleinen Ausflug braucht es offenbar keine Schuhe.',
    'Ich schaue nur. Einfach anfassen muss ja nicht sein.',
    'Die kleine Fellnase hat heute wohl viel vor.',
    'Da ist jemand deutlich näher an den interessanten Gerüchen.',
    'Ein tierischer Spaziergänger. Schön, Gesellschaft zu haben.',
    'Der Kleine nimmt sich wenigstens Zeit für jede Ecke.',
  ],
  wildlife: [
    'Da bewegt sich etwas zwischen dem Grün.',
    'Schau, ein Tier da draußen. Ganz ruhig bleiben.',
    'Ich beobachte lieber von hier und lasse es in Ruhe.',
    'Manchmal lohnt es sich, kurz stehen zu bleiben.',
    'Hier draußen sind wir wohl nur zu Besuch.',
    'Das Tier hat mich wahrscheinlich längst bemerkt.',
    'Ein bisschen Wildnis gehört auch zur Umgebung.',
    'Ich mache lieber einen Bogen, damit es Platz hat.',
    'So eine Begegnung macht den Ausflug besonders.',
    'Leise schauen ist hier vermutlich die beste Idee.',
    'Die Stadt endet, aber das Leben geht einfach weiter.',
    'Gut, dass hier noch Raum für Tiere bleibt.',
    'Ich bleibe auf Abstand. Das ist schließlich sein Revier.',
    'Das war ein schöner kleiner Moment am Wegesrand.',
  ],
  night: [
    'Nachts klingt die Stadt irgendwie anders.',
    'Noch eine Abendrunde, dann geht es nach Hause.',
    'Ich sollte meine Schlafenszeit nicht zu weit verschieben.',
    'Um diese Uhrzeit werden selbst meine Gedanken leiser.',
    'Die Nacht hat ihren eigenen Stadtplan.',
    'Ein kleiner Spaziergang vor dem Schlafen tut gut.',
    'Morgen früh werde ich diesen späten Ausflug bemerken.',
    'Ich mag die Stadt auch zu dieser späten Stunde.',
    'So langsam wäre mein Bett eine gute Adresse.',
    'Nachts sieht jede bekannte Ecke ein bisschen anders aus.',
    'Noch bis zur nächsten Ecke. Dann wirklich heim.',
    'Meine innere Uhr möchte gerade Feierabend machen.',
    'Die Stadt kommt offenbar auch spät noch nicht zur Ruhe.',
    'Abends wird aus einem Weg schnell ein kleiner Umweg.',
    'Ich habe heute genug erlebt. Zeit für den Heimweg.',
    'So eine Nachtluft hat schon etwas für sich.',
  ],
  lightsOn: [
    'Ah, jetzt sind die Lichter wieder an.',
    'So erkennt man gleich mehr von der Umgebung.',
    'Das Licht macht die Ecke deutlich freundlicher.',
    'Die Stadt hat gerade wieder die Augen aufgemacht.',
    'Mit Beleuchtung ist der Heimweg angenehmer.',
    'So, jetzt ist es hier wieder etwas gemütlicher.',
    'Da hat jemand den richtigen Schalter gefunden.',
    'Ein bisschen Licht verändert die ganze Stimmung.',
    'Jetzt kann ich wieder besser sehen, wo es weitergeht.',
    'Das ist gleich ein ganz anderer Anblick.',
    'Die Beleuchtung tut der Straße wirklich gut.',
    'Hell genug zum Weitergehen. Sehr praktisch.',
  ],
  lightsOff: [
    'Oh, gerade sind die Lichter ausgegangen.',
    'Da hat wohl jemand den Schalter umgelegt.',
    'Das sieht jetzt plötzlich ganz anders aus.',
    'Gut, dass ich den Weg hier schon kenne.',
    'Einmal Licht aus, und die ganze Stimmung wechselt.',
    'Ich schaue jetzt lieber etwas genauer auf den Weg.',
    'Die Stadt wirkt ohne Beleuchtung gleich stiller.',
    'Meine Augen müssen sich kurz umstellen.',
    'War das gerade der große Lichtschalter?',
    'Jetzt fehlen hier ein paar leuchtende Orientierungspunkte.',
    'Das Licht ist weg. Mein Heimweg leider noch nicht.',
    'So schnell wird aus einer Straße eine andere Kulisse.',
  ],
  rain: [
    'Natürlich liegt mein Schirm trocken zu Hause.',
    'Diese Pfütze umrunde ich lieber großzügig.',
    'Der Regen hat meinen Spaziergang nicht im Kalender gefunden.',
    'Meine Jacke gibt sich gerade wirklich Mühe.',
    'Nach Regen riecht die Stadt immer ein bisschen anders.',
    'Ich hätte die wasserdichten Schuhe nehmen sollen.',
    'Ein Dach über dem Kopf wäre jetzt ein gutes Ausflugsziel.',
    'Der Himmel gießt heute jedenfalls gründlich.',
    'Ich tue einfach so, als wäre das Absicht gewesen.',
    'Nasse Socken waren nicht Teil meines Tagesplans.',
    'Für die Pflanzen freue ich mich. Für meine Schuhe weniger.',
    'Die nächste Pfütze sieht tiefer aus, als sie sollte.',
    'Ein warmer Tee hat gerade deutlich an Reiz gewonnen.',
    'Dieser Regen könnte eine Pause durchaus vertragen.',
    'Ich gehe jetzt mit möglichst wenig Spritzwasser weiter.',
    'Mein Frisurplan wurde soeben vom Wetter gestrichen.',
  ],
  sun: [
    'Heute fühlt sich selbst der Umweg richtig an.',
    'Die Sonne macht aus dem Weg fast einen kleinen Urlaub.',
    'Gut, dass ich für eine Runde nach draußen gegangen bin.',
    'So ein heller Tag hebt gleich die Laune.',
    'Meine Sonnenbrille liegt bestimmt neben dem Regenschirm.',
    'Ein bisschen Sonne kann ich heute gut gebrauchen.',
    'Das ist eindeutig Wetter für einen längeren Spaziergang.',
    'Bei dem Licht sieht die Stadt gleich frischer aus.',
    'Ich genieße die Sonne lieber jetzt, solange sie da ist.',
    'Ein freier Platz im Schatten wäre später auch schön.',
    'Für heute hätte ich gern noch ein paar Stunden davon.',
    'Die Sonne hat meinen Heimweg gerade verlängert.',
  ],
  powerOutage: [
    'Hier scheint gerade Strom zu fehlen.',
    'Hoffentlich wird die Versorgung bald wieder stabil.',
    'Ohne Strom merkt man erst, wie viel davon abhängt.',
    'Da müsste sich jemand das Stromnetz ansehen.',
    'Ein verlässlicher Anschluss wäre hier wirklich hilfreich.',
    'Mit der Stromversorgung läuft gerade etwas nicht rund.',
    'Ich hoffe, die Elektrik bekommt bald wieder Anschluss.',
    'Diese Ecke braucht offenbar Hilfe vom Stromnetz.',
    'Strom ist so eine Sache, die man erst vermisst, wenn er fehlt.',
    'Das hier sieht nach einem Versorgungsproblem aus.',
    'Ein bisschen mehr Zuverlässigkeit beim Strom wäre schön.',
    'Hoffentlich ist das Stromproblem nur vorübergehend.',
  ],
  services: [
    'Gut, wenn wichtige Einrichtungen gleich in der Nähe sind.',
    'Eine Stadt braucht eben mehr als nur Wohnhäuser.',
    'Hier wird Arbeit gemacht, die uns allen hilft.',
    'Kurze Wege zu solchen Einrichtungen sind wirklich praktisch.',
    'Schön, dass die Versorgung hier einen Platz hat.',
    'Man vergisst schnell, was eine Stadt alles am Laufen hält.',
    'Von diesen Einrichtungen profitieren wir im Alltag alle.',
    'Gut, dass auch an die öffentlichen Aufgaben gedacht wird.',
    'Hier gehört nützliche Arbeit direkt zur Nachbarschaft.',
    'Eine funktionierende Stadt braucht solche Adressen.',
    'Es ist beruhigend, so etwas in der Umgebung zu wissen.',
    'Nicht alles Wichtige sieht man einer Straße sofort an.',
  ],
  fire: [
    'Da brennt es! Lieber schnell Abstand halten!',
    'Bitte nicht näher ran, das sieht gefährlich aus!',
    'Hoffentlich kommt die Feuerwehr rechtzeitig.',
    'Die Zufahrt muss für die Feuerwehr frei bleiben!',
    'Rauch da vorne. Ich gehe lieber in die andere Richtung.',
    'Weg vom Feuer, hier ist kein Platz zum Zuschauen!',
    'Ist jeder aus der Nähe des Brandes raus?',
    'So ein Feuer kann einem wirklich Angst machen.',
    'Ich halte mich von den Flammen fern.',
    'Bitte aufpassen, da vorne brennt etwas!',
    'Das ist jetzt ein Fall für die Feuerwehr.',
    'Nicht stehen bleiben, macht den Weg frei!',
    'Ich hoffe, alle haben den Brand bemerkt.',
    'Die Ecke meide ich, bis das Feuer gelöscht ist.',
    'Hier sollte wirklich niemand näher herangehen.',
    'Lieber einen großen Umweg als direkt am Feuer vorbei.',
  ],
  industry: [
    'Hier merkt man, dass die Stadt auch arbeiten muss.',
    'Die Fabriken prägen diese Ecke ganz schön.',
    'Für meine nächste Runde suche ich mir mehr Grün.',
    'Hier entsteht wohl ein guter Teil von dem, was wir brauchen.',
    'Wohnen und Industrie brauchen einen vernünftigen Abstand.',
    'Diese Gegend klingt schon deutlich nach Arbeit.',
    'Ein paar grüne Streifen würden hier gut passen.',
    'Ich gehe jetzt lieber wieder Richtung Wohnviertel.',
    'So sieht die produktive Seite unserer Stadt aus.',
    'Zwischen all den Betrieben wirkt man selbst ziemlich klein.',
    'Hier ist die Stadt eher praktisch als gemütlich.',
    'Ein schöner Ausgleich dazu wäre ein großer Park.',
    'Die Industrie gehört dazu, aber Abstand auch.',
    'Diese Ecke ist eher Arbeitsplatz als Spazierziel.',
  ],
  stadium: [
    'Am Stadion fühlt sich selbst ein Spaziergang sportlich an.',
    'Hier möchte ich irgendwann mal ein Spiel sehen.',
    'Ich wäre schon nach der Aufwärmrunde erschöpft.',
    'So ein Stadion ist ein ordentlicher Orientierungspunkt.',
    'Meine Kondition reicht heute nur bis an den Rand.',
    'Ob ich fürs nächste Spiel noch jemanden begeistern kann?',
    'Hier bekommt man direkt Lust auf einen Sportnachmittag.',
    'Auf der Tribüne wäre ich vermutlich ausdauernder.',
    'Das Stadion kennt inzwischen wahrscheinlich jeder hier.',
    'Ich könnte auch mal wieder etwas Sport machen. Könnte.',
    'Ein Spielbesuch wäre eine gute Idee fürs Wochenende.',
    'An dieser Adresse zählt mein Spaziergang fast als Training.',
  ],
  airport: [
    'In Flughafennähe bekomme ich immer ein bisschen Fernweh.',
    'Andere verreisen, ich drehe erst mal eine Runde.',
    'Mein nächster Ausflug braucht vielleicht doch ein Ticket.',
    'Hier beginnt für viele bestimmt eine große Reise.',
    'Ich habe keinen Koffer dabei, nur ein bisschen Fernweh.',
    'So ein Flughafen verbindet die Stadt mit ziemlich viel Welt.',
    'Ein Urlaub wäre schön. Erst mal reicht der Spaziergang.',
    'Ich mag die Vorstellung, von hier irgendwohin zu starten.',
    'Zum Glück muss ich heute keine Abflugzeit im Kopf behalten.',
    'Am Flughafen denke ich sofort an lange Reisen.',
    'Meine Bordkarte besteht heute aus zwei bequemen Schuhen.',
    'Von hier aus ist die Welt offenbar ein Stück näher.',
  ],
} as const;

export type CitizenDialogueTopic = keyof typeof CITIZEN_LINES;

/** Matching indexes identify one observation in both languages. */
export const CITIZEN_LINES_EN = {
  ...CITIZEN_LINES_EN_A,
  ...CITIZEN_LINES_EN_B,
  ...CITIZEN_LINES_EN_C,
} as const satisfies {
  [Topic in CitizenDialogueTopic]: readonly string[] & { readonly length: typeof CITIZEN_LINES[Topic]['length'] };
};

export interface CitizenDialoguePair { readonly de: string; readonly en: string; }

export const CITIZEN_SPEECH_LIMITS = Object.freeze({ actors: 256, actorHistory: 8, globalHistory: 12 });

interface SpeakerMemory { recent: string[]; bags: Map<CitizenDialogueTopic, number[]>; }

/**
 * Each resident uses every authored line of a topic before starting its next
 * shuffled bag. Recent citywide lines are avoided when possible, so neighbours
 * do not form a chorus. Only the bounded active-resident LRU keeps personal bags.
 * No wall clock or Math.random is used, making simulation replays reproducible.
 */
export function createCitizenSpeechSelector(seed = 1) {
  let randomState = (Number.isFinite(seed) ? Math.trunc(seed) : 1) >>> 0;
  randomState ||= 0x9e3779b9;
  const actors = new Map<number, SpeakerMemory>();
  const recentGlobal: string[] = [];
  const nextRandom = () => {
    randomState ^= randomState << 13;
    randomState ^= randomState >>> 17;
    randomState ^= randomState << 5;
    return (randomState >>> 0) / 0x100000000;
  };
  const remember = (history: string[], line: string, limit: number) => {
    history.push(line);
    if (history.length > limit) history.shift();
  };

  const pickPair = (topic: CitizenDialogueTopic, actorId: number): CitizenDialoguePair => {
      let actor = actors.get(actorId);
      if (!actor) actor = { recent: [], bags: new Map() };
      // Refresh insertion order so frequently seen residents retain their memory.
      actors.delete(actorId);
      actors.set(actorId, actor);
      if (actors.size > CITIZEN_SPEECH_LIMITS.actors) actors.delete(actors.keys().next().value!);

      const lines: readonly string[] = CITIZEN_LINES[topic];
      let bag = actor.bags.get(topic);
      if (!bag?.length) {
        bag = Array.from({ length: lines.length }, (_, index) => index);
        for (let i = bag.length - 1; i > 0; i--) {
          const j = Math.floor(nextRandom() * (i + 1));
          [bag[i], bag[j]] = [bag[j], bag[i]];
        }
        actor.bags.set(topic, bag);
      }

      // Complete the bag even under a busy chorus. Personal repetition takes
      // precedence over global recency when both cannot be satisfied at once.
      let selected = bag.findIndex(index => !actor.recent.includes(lines[index]) && !recentGlobal.includes(lines[index]));
      if (selected < 0) selected = bag.findIndex(index => !actor.recent.includes(lines[index]));
      if (selected < 0) selected = bag.findIndex(index => lines[index] !== actor.recent.at(-1));
      if (selected < 0) selected = 0;
      const index = bag.splice(selected, 1)[0];
      const line = lines[index];
      remember(actor.recent, line, CITIZEN_SPEECH_LIMITS.actorHistory);
      remember(recentGlobal, line, CITIZEN_SPEECH_LIMITS.globalHistory);
      return { de: line, en: CITIZEN_LINES_EN[topic][index] };
  };

  return {
    // Both entry points consume exactly one shared language-independent bag.
    pick(topic: CitizenDialogueTopic, actorId: number): string { return pickPair(topic, actorId)[getLocale()]; },
    // Active bubbles keep this pair, so changing language does not select again.
    pickPair,
    forget(actorId: number): void { actors.delete(actorId); },
    clear(): void { actors.clear(); recentGlobal.length = 0; },
    getDebug() {
      return {
        actors: actors.size,
        topicBags: [...actors.values()].reduce((sum, actor) => sum + actor.bags.size, 0),
        actorHistory: [...actors.values()].reduce((sum, actor) => sum + actor.recent.length, 0),
        globalHistory: recentGlobal.length,
      };
    },
  };
}
