import './style.css';
import './expansion-ui.css';
import { createElement, icons } from 'lucide';
import { createCity, build, tick, recalculate, serializeCity, deserializeCity, takeLoan, repayLoan, triggerDisaster, TOOL_DEFS, expandCity, previewBuild, getFootprint, isBuildingAnchor, applyCitizenIncident } from './simulation';
import { createCityScene } from './scene';
import { getRank, isToolUnlocked, claimQuest, startChallenge, RANKS, updateProgression } from './progression';
import { renderProgressionSidebar, renderProgressionDialog, type ProgressionTab } from './progression-ui';
import { loadSavedCity, saveCityRaw, backupLegacy, safePreferenceGet, safePreferenceSet } from './storage';
import type { CityState, Tool, Overlay, Point, Tile, TileKind, CitySceneApi, BuildOptions, PreviewInfo, Weather, DisasterKind, VehicleHover, DrivingStatus } from './types';

const $ = <T extends HTMLElement = HTMLElement>(q:string) => document.querySelector<T>(q)!;
const icon = (name:string, cls='') => `<i data-lucide="${name}" class="${cls}"></i>`;
const fmt = (n:number) => Math.round(n).toLocaleString('de-DE');
const euro = (n:number) => `${fmt(n)} €`;
const MONTHS=['Jan','Feb','Mär','Apr','Mai','Jun','Jul','Aug','Sep','Okt','Nov','Dez'];
const clamp = (v:number,min:number,max:number) => Math.max(min,Math.min(max,v));
const escape = (s:string) => s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
let state = createCity(7341);
let saved = false;
let loadError = '';
let loadNotice = '';
let saveBlocked = false;
let recoveryRaw: string | null = null;
let savePending = false;
let saveFailed = false;
let nextAutosave = Date.now() + 30000;
let saveDebounce: ReturnType<typeof setTimeout>;
let sceneSize = 0;
let buildingRotation: 0|1|2|3 = 0;
let progressionTab: ProgressionTab = 'quests';
let driving = false;
let hoveredVehicle: number | null = null;
let lastPreview: PreviewInfo | null = null;
let vehicleHoverTimer: ReturnType<typeof setTimeout>;
let lastRank = 0;
let victoryAnnounced=false;
let tool:Tool='inspect', category='favorites', brush=1, overlay:Overlay='none', night=false, grid=false;
let scene:CitySceneApi;
let selected:Point|null=null;
let modal='';
let undoStack:string[]=[];
let lastAutosave=Date.now();
let tickAccumulator=0;
let previousTime=performance.now();
let lastEvent=state.events[0]?.id??0;
let toastTimer:ReturnType<typeof setTimeout>;
let minimizeAdvisor = false;
let buildCount=0;
let quality:"performance"|"balanced"|"ultra"="balanced";
let frameCount=0;
let fps=60;
const TOOL_META:Record<string,{icon:string,label:string}>={
 inspect:{icon:'mouse-pointer-2',label:'Auswählen'},road:{icon:'route',label:'Straße'},rail:{icon:'train-front',label:'Schiene'},residential:{icon:'house',label:'Wohnen'},commercial:{icon:'building-2',label:'Gewerbe'},industrial:{icon:'factory',label:'Industrie'},power:{icon:'zap',label:'Kraftwerk'},waterpump:{icon:'droplets',label:'Wasserturm'},park:{icon:'trees',label:'Park'},tree:{icon:'tree-pine',label:'Bäume'},police:{icon:'shield-check',label:'Polizei'},fire:{icon:'flame',label:'Feuerwehr'},hospital:{icon:'heart-pulse',label:'Klinik'},school:{icon:'graduation-cap',label:'Schule'},stadium:{icon:'trophy',label:'Stadion'},airport:{icon:'plane',label:'Flughafen'},seaport:{icon:'ship',label:'Hafen'},bulldoze:{icon:'pickaxe',label:'Abreißen'},pan:{icon:'hand',label:'Bewegen'},citizen:{icon:'person-standing',label:'Bewohner'},pipe:{icon:'pipette',label:'Wasserrohre'},powerline:{icon:'utility-pole',label:'Stromleitung'},raise:{icon:'mountain',label:'Anheben'},lower:{icon:'shovel',label:'Absenken'},level:{icon:'align-vertical-justify-center',label:'Einebnen'},wind:{icon:'wind',label:'Windkraft'},solar:{icon:'sun',label:'Solarpark'},university:{icon:'graduation-cap',label:'Universität'},recycling:{icon:'recycle',label:'Recycling'}};
const CATEGORIES=[['favorites','sparkles','Schnellzugriff'],['zones','grid-2x2','Zonen'],['transport','route','Verkehr'],['utilities','zap','Versorgung'],['services','landmark','Stadtdienste'],['nature','trees','Natur'],['terrain','mountain','Gelände'],['special','building','Großprojekte']];
const GROUP_TOOLS:Record<string,Tool[]>={favorites:['inspect','pan','road','residential','commercial','industrial','park','bulldoze','citizen'],zones:['residential','commercial','industrial'],transport:['road','rail'],utilities:['power','waterpump','powerline','pipe','wind','solar'],services:['police','fire','hospital','school','university','recycling'],nature:['park','tree','bulldoze'],terrain:['raise','lower','level'],special:['stadium','airport','seaport']};

$('#app').innerHTML=`
  <main id="game" aria-label="Neustadt 3D Städtebauspiel">
    <div id="world" aria-label="Interaktive dreidimensionale Stadt"></div>
    <header class="topbar">
      <a class="brand" href="#" id="brand-help" aria-label="Über Neustadt"><span class="brand-symbol">${icon('building-2')}</span><span>NEUSTADT<small>DEINE STADT. DEINE GESCHICHTE.</small></span></a>
      <div class="city-heading"><span class="eyebrow">BÜRGERMEISTERBÜRO</span><button id="city-name" title="Stadt verwalten"></button></div>
      <div class="top-stats">
        <button class="stat" id="population-stat" title="Bevölkerungsstatistik">${icon('users')}<span><small>Einwohner</small><strong id="population">0</strong></span><span class="stat-trend" id="population-trend">↗</span></button>
        <button class="stat money-stat" id="budget-stat" title="Stadthaushalt öffnen">${icon('wallet')}<span><small>Stadtkasse</small><strong id="money">0 €</strong></span><span id="balance" class="stat-trend"></span></button>
        <button class="stat happiness-stat" id="happiness-stat" title="Stadtbericht öffnen">${icon('smile')}<span><small>Zufriedenheit</small><strong id="happiness">0 %</strong></span></button>
      </div>
      <div class="top-actions"><button class="icon-btn" id="goals-btn" title="Ausbaustufen, Aufträge und Challenges">${icon('flag')}</button><button class="icon-btn" id="graphics-btn" title="Grafik und Beleuchtung">${icon('monitor-cog')}</button><button class="icon-btn" id="save-btn" title="Stadt speichern (Strg+S)">${icon('save')}</button><button class="icon-btn" id="menu-btn" title="Stadtmenü">${icon('menu')}</button></div>
    </header>
    <div class="viewbar"><div class="live-label"><span class="live-dot"></span><span id="city-status">DEINE STADT LEBT</span></div><div class="view-switch"><label for="overlay-select">${icon('layers')}</label><select id="overlay-select" aria-label="Datenansicht"><option value="none">Stadtansicht</option><option value="power">Stromversorgung</option><option value="water">Wasserversorgung</option><option value="landvalue">Grundstückswert</option><option value="pollution">Umweltbelastung</option><option value="traffic">Verkehrsdichte</option><option value="terrain">Geländehöhen</option></select><span id="day-clock">14:00</span><span class="view-divider"></span><button id="building-lights-btn" title="Stadtbeleuchtung ein-/ausschalten (L)" aria-label="Stadtbeleuchtung" aria-pressed="true">${icon('lightbulb')}</button><button id="grid-btn" title="Raster einblenden (G)" aria-pressed="false">${icon('grid-2x2')}</button><button id="night-btn" title="Tag / Nacht (N)" aria-pressed="false">${icon('sun')}</button></div></div>
    <aside class="left-column">
      <section class="advisor panel" id="advisor"><div class="panel-kicker"><span>${icon('sprout')} DEIN NÄCHSTES KAPITEL</span><button class="small-icon" id="advisor-close" title="Hinweise einklappen">${icon('minus')}</button></div><h1>Platz für morgen.</h1><p>Aus einer guten Nachbarschaft wird eine großartige Stadt.</p><div class="goal-label"><span id="goal-title">Eine Stadt wächst</span><strong id="goal-progress">0 / 5.000</strong></div><div class="progress-track"><div id="goal-bar"></div></div><div class="goal-reward">${icon('gift')} <span id="goal-reward">Nächster Meilenstein: 5.000 Einwohner</span></div><div class="advisor-divider"></div><div class="checklist"><div id="check-roads">${icon('circle')}<span>Straßen als Verbindung bauen</span></div><div id="check-zones">${icon('circle')}<span>Raum zum Wohnen schaffen</span></div><div id="check-services">${icon('circle')}<span>Strom und Wasser bereitstellen</span></div></div><button class="text-link" id="help-btn">So funktioniert deine Stadt ${icon('arrow-up-right')}</button></section>
      <section class="demand panel"><div class="section-label">${icon('chart-no-axes-combined')} NACHFRAGE <span class="info-dot" title="Hohe Nachfrage fördert das Wachstum versorgter Zonen.">i</span></div><div class="demand-item"><span><b class="dot residential"></b>Wohnen</span><div class="demand-track"><i id="demand-r"></i></div><b id="demand-r-val"></b></div><div class="demand-item"><span><b class="dot commercial"></b>Gewerbe</span><div class="demand-track"><i id="demand-c"></i></div><b id="demand-c-val"></b></div><div class="demand-item"><span><b class="dot industrial"></b>Industrie</span><div class="demand-track"><i id="demand-i"></i></div><b id="demand-i-val"></b></div></section>
      <button class="news-button" id="news-btn">${icon('newspaper')}<span><small>NEUES AUS LINDENBUCHT</small><strong id="latest-news">Deine Stadt wartet auf dich.</strong></span>${icon('chevron-right')}</button>
    </aside>
    <div id="overlay-legend" class="panel hidden"></div>
    <aside id="inspector" class="panel hidden"></aside>
    <div class="camera-controls"><button id="pan-btn" title="Kamera verschieben (M)">${icon('hand')}</button><button id="overview-btn" title="Ganze Region ansehen">${icon('globe')}</button><button id="zoom-in" title="Vergrößern">${icon('plus')}</button><button id="zoom-out" title="Verkleinern">${icon('minus')}</button><span></span><button id="rotate-left" title="Kamera drehen (Q)">${icon('rotate-ccw')}</button><button id="rotate-right" title="Kamera drehen (E)">${icon('rotate-cw')}</button><button id="camera-home" title="Zur Innenstadt">${icon('scan')}</button><button id="camera-help" title="Kamera und Maus bedienen">${icon('circle-help')}</button></div>
    <div class="map-widget panel"><div class="map-heading"><span>${icon('map')} REGION</span><span class="north">N ↑</span></div><canvas id="minimap" width="160" height="136" aria-label="Übersichtskarte; zum Navigieren klicken"></canvas><div class="map-caption">Lindenbucht <span>40 × 40</span></div></div>
    <button id="vehicle-hotspot" class="hidden" title="Dieses Auto selbst fahren"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7"><circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="2"/><path d="M3.6 8.8 10 12m4 0 6.4-3.2M12 14v7"/></svg><span>Selbst fahren</span></button><div id="drive-hud" class="drive-hud hidden"><strong id="drive-speed">0 <small>km/h</small></strong><div><p>W / ↑ Beschleunigen · S / ↓ Bremsen</p><p>A / D Lenken · Leertaste + Lenken: Driften</p><p id="drive-status"></p></div><button id="exit-drive">${icon('log-out')} ESC · Aussteigen</button></div><div id="build-preview" class="build-preview hidden" aria-live="polite"></div><div id="tile-tooltip" class="hidden"></div>
    <div id="toast" role="status" class="toast hidden"></div>
    <footer class="build-dock"><div class="dock-top"><nav class="category-tabs" aria-label="Baukategorien">${CATEGORIES.map(([id,ic,label])=>`<button data-category="${id}" class="${id===category?'active':''}">${icon(ic)}<span>${label}</span></button>`).join('')}</nav><div class="history-buttons"><button id="undo-btn" title="Letzten Bau rückgängig machen (Strg+Z)">${icon('undo-2')}</button><button id="help-shortcut" title="Spielhilfe (H)">${icon('circle-help')}</button></div></div><div class="dock-main"><div id="tool-list"></div><div class="time-controls"><div class="date-display">${icon('calendar-days')}<strong id="game-date">JAN 2000</strong><span id="season">FRÜHLING</span></div><div class="speed-buttons"><button data-speed="0" title="Pause (Leertaste)" aria-label="Pause">${icon('pause')}</button><button data-speed="1" title="Normale Geschwindigkeit" aria-label="Normale Geschwindigkeit">${icon('play')}<span>1×</span></button><button data-speed="2" title="Doppelte Geschwindigkeit" aria-label="Doppelte Geschwindigkeit">${icon('fast-forward')}<span>2×</span></button><button data-speed="3" title="Dreifache Geschwindigkeit" aria-label="Dreifache Geschwindigkeit">${icon('fast-forward')}<span>3×</span></button></div></div></div><div class="dock-bottom"><div class="tool-hint" id="tool-hint"></div><div class="brush-control" id="brush-control"><span>Pinsel</span><button data-brush="1" class="active">1</button><button data-brush="3">3</button><button data-brush="5">5</button><button data-brush="8">8</button></div><button class="rotate-building hidden" id="rotate-building" title="Gebäude drehen (R)">${icon('rotate-cw')} <span>R · Drehen</span></button><span class="navigation-hint">${icon('mouse')} M / Hand: Bewegen · Rechts: Drehen · Rad: Zoom <span class="separator">/</span> <span id="autosave-status">Speicher wird vorbereitet</span></span></div></footer>
    <div id="modal-root"></div><input id="import-file" type="file" accept=".json,application/json" hidden/>
    <div id="loading-screen"><div class="loading-brand">${icon('building-2')} NEUSTADT</div><span>Deine Stadt wird lebendig …</span><div class="loading-line"></div></div>
  </main>`;

function refreshIcons(root?:HTMLElement){ (root??document).querySelectorAll<HTMLElement>('i[data-lucide]').forEach(el=>{const name=el.dataset.lucide!.split('-').map(v=>v[0].toUpperCase()+v.slice(1)).join('');const node=icons[name as keyof typeof icons];if(node){const svg=createElement(node);svg.setAttribute('stroke-width','1.65');if(el.className)svg.setAttribute('class',el.className);el.replaceWith(svg);}}); }
function toast(message:string,type:'good'|'warning'|'info'='info'){const el=$('#toast'); el.innerHTML=`${icon(type==='good'?'check-circle-2':type==='warning'?'triangle-alert':'info')}<span>${escape(message)}</span>`;el.className=`toast ${type}`;refreshIcons(el);clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.classList.add('hidden'),4600);}
async function save(show=true){
 if(saveBlocked){if(show)toast('Der bisherige Spielstand bleibt geschützt. Exportiere die aktuelle Stadt oder starte/importiere ausdrücklich eine neue.','warning');return;}
 if(savePending){if(show)toast('Deine Stadt wird bereits gespeichert.');return;}
 nextAutosave=Date.now()+30000;savePending=true;
 try{const raw=serializeCity(state);await saveCityRaw(raw);lastAutosave=Date.now();saveFailed=false;$('#autosave-status').textContent='Lokal gesichert';if(show)toast(`${state.name} gespeichert.`,'good');}
 catch(error){nextAutosave=Date.now()+120000;$('#autosave-status').textContent='Speicherfehler · bitte exportieren';if(show||!saveFailed)toast(error instanceof Error?error.message:'Speichern fehlgeschlagen. Exportiere die Stadt im Menü.','warning');saveFailed=true;}
 finally{savePending=false;}
}
function scheduleSave(){clearTimeout(saveDebounce);saveDebounce=setTimeout(()=>void save(false),1000);}
function clearUndo(){undoStack=[];$('#undo-btn')?.setAttribute('disabled','');}
function cityChanged(){clearUndo();updateProgression(state);renderStats();renderTools();scheduleSave();}

function snapshot(){undoStack.push(serializeCity(state));if(undoStack.length>10)undoStack.shift();}
function undo(){if(!undoStack.length)return toast('Es gibt noch keinen Bau zum Rückgängigmachen.');state=deserializeCity(undoStack.pop()!);syncScene();renderStats();renderInspector();scheduleSave();toast('Letzten Bau rückgängig gemacht.');}
function selectTool(value:Tool){
 tool=value;scene?.setTool(tool,brush,buildingRotation);renderTools();
 $('#pan-btn')?.classList.toggle('active',tool==='pan');
 if(tool!=='inspect'){$('#inspector').classList.add('hidden');selected=null;}
 if(tool==='pipe'){setOverlay('water');$<HTMLSelectElement>('#overlay-select').value='water';}
 if(tool==='powerline'){setOverlay('power');$<HTMLSelectElement>('#overlay-select').value='power';}
 if(!isToolUnlocked(state,tool)){const rank=RANKS.find(r=>r.unlocks.includes(tool));toast(`Bau verfügbar ab ${rank?.name??'einer höheren Ausbaustufe'} · ${fmt(rank?.population??0)} Einwohner.`);}
}
function renderTools(){
 $('#tool-list').innerHTML=GROUP_TOOLS[category].map(t=>{const meta=TOOL_META[t],def=TOOL_DEFS[t],locked=!isToolUnlocked(state,t),dims=def?.footprint;return `<button class="build-tool ${tool===t?'selected':''} ${t} ${locked?'locked':''}" data-tool="${t}" title="${escape(def?.description??(t==='pan'?'Mit links ziehen oder WASD verwenden.':t==='citizen'?'Bewohner greifen, heben und wieder absetzen.':'Gebäude auswählen und Informationen anzeigen'))}" aria-pressed="${tool===t}"><span class="tool-icon">${icon(meta.icon)}</span><span class="tool-name">${meta.label}</span><small>${['inspect','pan','citizen'].includes(t)?(t==='pan'?'M · Ziehen':t==='citizen'?'C · Greifen':'Erkunden'):t==='bulldoze'?'2–25 €':`${fmt(def?.cost??0)} €`}</small>${dims?`<span class="footprint-badge">${dims[0]}×${dims[1]}</span>`:''}${locked?`<span class="tool-lock">${icon('lock-keyhole')}</span>`:tool===t?'<span class="selected-indicator"></span>':''}</button>`;}).join('');
 document.querySelectorAll<HTMLButtonElement>('[data-tool]').forEach(b=>b.onclick=()=>selectTool(b.dataset.tool as Tool));
 const def=TOOL_DEFS[tool];const desc=tool==='inspect'?'Klicke auf ein Gebäude, um mehr zu erfahren.':tool==='pan'?'Links ziehen oder WASD · rechts drehen · Mausrad zoomen.':tool==='citizen'?'Figur greifen und ziehen · sanft absetzen zum Weiterlaufen · schneller Wurf hat Folgen.':tool==='level'?'Erster Klick bestimmt die Zielhöhe. Zum Glätten über freie Flächen ziehen.':tool==='bulldoze'?'Klicken oder ziehen. Große Gebäude werden vollständig abgerissen.':def?.description??'Klicken oder ziehen, um zu bauen.';
 $('#tool-hint').innerHTML=`<span class="hint-dot" style="background:${def?.color??'#8aa89b'}"></span><strong>${TOOL_META[tool]?.label??tool}</strong><span>${escape(desc)}</span>`;
 $('#brush-control').style.display=def?.footprint||['inspect','pan','citizen','road','rail','pipe','powerline'].includes(tool)?'none':'flex';
 $('#rotate-building').classList.toggle('hidden',!def?.footprint);refreshIcons($('#tool-list'));
}
function progressionBindings(container:HTMLElement){
 container.querySelectorAll<HTMLElement>('[data-open-progress]').forEach(b=>b.onclick=()=>{progressionTab=b.dataset.openProgress as ProgressionTab;openModal('progression');});
 container.querySelectorAll<HTMLElement>('[data-progress-tab]').forEach(b=>b.onclick=()=>{progressionTab=b.dataset.progressTab as ProgressionTab;renderModal();});
 container.querySelectorAll<HTMLElement>('[data-claim-quest]').forEach(b=>b.onclick=()=>{const result=claimQuest(state,b.dataset.claimQuest!);if(result.ok)cityChanged();toast(result.message,result.ok?'good':'warning');if(modal==='progression')renderModal();});
 container.querySelectorAll<HTMLElement>('[data-start-challenge]').forEach(b=>b.onclick=()=>{const result=startChallenge(state,b.dataset.startChallenge!);if(result.ok)cityChanged();toast(result.message,result.ok?'good':'warning');renderModal();});
}

function renderStats(){
 const s=state.stats; $('#city-name').innerHTML=`${escape(state.name)} ${icon('chevron-down')}`;$('#population').textContent=fmt(s.population);const previous=state.history.at(-2)?.population??s.population;const change=s.population-previous;$('#population-trend').textContent=change===0?'–':`${change>0?'+':''}${fmt(change)}`;$('#population-trend').classList.toggle('negative',change<0);$('#money').textContent=euro(state.money);$('#happiness').textContent=`${fmt(s.happiness)} %`;$('#balance').textContent=`${s.balance>=0?'+':''}${euro(s.balance)}/M`;$('#balance').classList.toggle('negative',s.balance<0);$('#game-date').textContent=`${MONTHS[state.month%12].toUpperCase()} ${2000+Math.floor(state.month/12)}`;
 $('#season').textContent=['WINTER','WINTER','FRÜHLING','FRÜHLING','FRÜHLING','SOMMER','SOMMER','SOMMER','HERBST','HERBST','HERBST','WINTER'][state.month%12];$('#city-status').textContent=state.speed===0?'ZEIT FÜR DEINE IDEEN':'DEINE STADT LEBT';$('.live-dot').classList.toggle('paused',state.speed===0);
 document.querySelectorAll<HTMLButtonElement>('[data-speed]').forEach(b=>{b.classList.toggle('active',Number(b.dataset.speed)===state.speed);b.setAttribute('aria-pressed',String(Number(b.dataset.speed)===state.speed));});
 [['r',s.residentialDemand],['c',s.commercialDemand],['i',s.industrialDemand]].forEach(([key,val])=>{$(`#demand-${key}`).style.width=`${clamp(Number(val),0,100)}%`;$(`#demand-${key}-val`).textContent=`${Math.round(Number(val))}%`;});
 $('#advisor').innerHTML=renderProgressionSidebar(state);progressionBindings($('#advisor'));$('#advisor').classList.toggle('hidden',minimizeAdvisor);const latest=state.events[0];$('#latest-news').textContent=latest?.title??'Deine Stadt wartet auf dich.';$('.news-button small').textContent=`NEUES AUS ${state.name.toUpperCase()}`;$('.map-caption').innerHTML=`${escape(state.name)} <span>${state.size} × ${state.size}</span>`;
 $('#undo-btn').toggleAttribute('disabled',!undoStack.length);renderLightSwitch();renderDayClock();drawMinimap();refreshIcons($('.topbar'));refreshIcons($('#advisor'));
}
function drawMinimap(){
 const c=$<HTMLCanvasElement>('#minimap'),ctx=c.getContext('2d')!;const colors:Record<string,string>={tree:'#507452',water:'#70abbc',road:'#ede7d6',rail:'#56626b',residential:'#85ad71',commercial:'#497f93',industrial:'#b99556',park:'#528c68',power:'#cf9b47',waterpump:'#548fa9',rubble:'#8e6552',university:'#a198b3',solar:'#476a8b',wind:'#d5dcc9'};const sx=c.width/state.size,sy=c.height/state.size;
 for(const t of state.tiles){ctx.fillStyle=t.fire>0?'#eb6651':colors[t.kind]??(t.kind==='empty'?`hsl(${94+t.elevation*1.5} 22% ${66-t.elevation*2}%)`:'#d4d4c4');ctx.fillRect(t.x*sx,t.z*sy,Math.ceil(sx),Math.ceil(sy));if(overlay==='water'&&t.hasPipe){ctx.fillStyle='#7cdbe7';ctx.fillRect(t.x*sx,t.z*sy,Math.ceil(sx),Math.ceil(sy));}if(overlay==='power'&&t.hasPowerLine){ctx.fillStyle=t.powered?'#f5d47a':'#d97359';ctx.fillRect(t.x*sx,t.z*sy,Math.ceil(sx),Math.ceil(sy));}}
}

function renderInspector(){
 if(!selected)return;let t=state.tiles[selected.z*state.size+selected.x];if(!t)return;if(t.anchor>=0)t=state.tiles[t.anchor]??t;
 const def=TOOL_DEFS[t.kind],m=TOOL_META[t.kind],cells=getFootprint(state,t);const dims=def?.footprint;const pop=t.kind==='residential'?[0,12,28,52,88][t.level]:0;const selectedAnchor={x:t.x,z:t.z};
 $('#inspector').innerHTML=`<div class="panel-kicker"><span>GRUNDSTÜCK ${t.x+1} · ${t.z+1}</span><button id="inspector-close" class="small-icon" title="Details schließen">${icon('x')}</button></div><div class="inspector-icon ${t.kind}">${icon(m?.icon??(t.kind==='water'?'waves':'sprout'))}</div><h2>${m?.label??(t.kind==='empty'?'Freies Bauland':t.kind==='water'?'Küstengewässer':t.kind==='rubble'?'Trümmerfeld':t.kind)}</h2><p>${escape(def?.description??'Ein Stück deiner Region voller Möglichkeiten.')}</p><div class="inspector-tags"><span>${dims?`${dims[t.rotation%2?1:0]} × ${dims[t.rotation%2?0:1]} Felder`:t.level>0?`Gebäudestufe ${t.level}`:'Unbebaut'}</span><span>${fmt(t.elevation*10)} m Höhe</span>${t.fire>0?'<span class="danger">Brand!</span>':''}</div><div class="inspector-rows">${[['Straßenanschluss',t.connected?'Angeschlossen':'Kein Anschluss'],['Stromversorgung',t.powered?'Versorgt':'Nicht versorgt'],['Wasserversorgung',t.watered?'Versorgt':'Nicht versorgt'],['Wasserrohr',cells.some(p=>state.tiles[p.z*state.size+p.x].hasPipe)?'Vorhanden':'Keines'],['Stromleitung',cells.some(p=>state.tiles[p.z*state.size+p.x].hasPowerLine)?'Vorhanden':'Keine'],['Grundstückswert',`${fmt(t.landValue)} / 100`],['Umweltbelastung',`${fmt(t.pollution)} %`],...(pop?[['Wohnplätze',fmt(pop)]]:[])].map(([a,b])=>`<div><span>${a}</span><strong>${b}</strong></div>`).join('')}</div>${!['empty','water'].includes(t.kind)||t.hasPipe||t.hasPowerLine?`<button id="demolish-selected" class="button secondary">${icon('pickaxe')} ${dims?'Gesamtes Gebäude':'Grundstück'} abreißen</button>`:''}`;
 $('#inspector').classList.remove('hidden');$('#inspector-close').onclick=()=>{$('#inspector').classList.add('hidden');selected=null;};const b=$('#demolish-selected');if(b)b.onclick=()=>{paint([selectedAnchor],'bulldoze');renderInspector();};refreshIcons($('#inspector'));
}

function paint(points:Point[],override?:Tool,options:BuildOptions={}){
 const use=override??tool;if(['inspect','pan','citizen'].includes(use))return;
 const preview=previewBuild(state,points,use,options);if(!preview.count||preview.cost>state.money)return toast(preview.message,'warning');
 const previous=serializeCity(state);const result=build(state,points,use,options);
 if(result.ok){undoStack.push(previous);if(undoStack.length>10)undoStack.shift();buildCount+=result.count;syncScene();renderStats();renderTools();scheduleSave();toast(result.message,'good');}else toast(result.message,'warning');
}
function renderBuildPreview(info:PreviewInfo|null){
 lastPreview=info;const el=$('#build-preview');if(!info||['inspect','pan','citizen'].includes(info.tool)){el.classList.add('hidden');return;}
 const valid=info.count>0&&info.cost<=state.money;const dims=info.footprint;
 el.innerHTML=`<div class="preview-title">${icon(TOOL_META[info.tool]?.icon??'construction')}<strong>${TOOL_META[info.tool]?.label??info.tool}</strong>${dims?`<span>${dims[0]} × ${dims[1]}</span>`:''}</div><div class="preview-cost"><b>${euro(info.cost)}</b><span>${info.valid.length} Felder${info.invalid.length?` · ${info.invalid.length} ${info.message.includes('bereits')?'unverändert':'nicht geändert'}`:''}</span></div><p>${escape(info.message)}</p>${info.elevation!==undefined?`<small>${fmt(info.elevation*10)} m · ${dims?'R drehen':'Loslassen zum Anwenden'}</small>`:''}`;
 el.className=`build-preview ${valid?'valid':'invalid'}`;el.style.left=`${clamp(info.screenX+22,290,window.innerWidth-280)}px`;el.style.top=`${clamp(info.screenY-40,100,window.innerHeight-310)}px`;refreshIcons(el);
}
function createScene(){return createCityScene($('#world'),state,{onHover:p=>{if(!p)$('#tile-tooltip').classList.add('hidden');},onPaint:(points,options)=>paint(points,undefined,options),onSelect:p=>{selected=p;renderInspector();},onPreview:renderBuildPreview,onVehicleHover:showVehicleHover,onDriveStatus:updateDriveHud,onCitizenIncident:incident=>{const result=applyCitizenIncident(state,incident);if(result.ok){clearUndo();syncScene();renderStats();scheduleSave();toast(result.message,incident.witnessed?'warning':'info');}}});}
function syncScene(reset=false){
 if(!scene||sceneSize!==state.size){scene?.dispose();scene=createScene();sceneSize=state.size;scene.setGraphicsQuality(quality);scene.setTool(tool,brush,buildingRotation);const savedHour=state.settings.timeOfDay,savedCycle=state.settings.dayNightCycle;scene.setTimeOfDay(savedHour);scene.setDayNightCycle(savedCycle);scene.setBuildingLights(state.settings.buildingLights);scene.setOverlay(overlay);scene.setGrid(grid);scene.setWeather(state.settings.weather);}
 else scene.update(state);
 if(reset)scene.resetCamera();
}

function showVehicleHover(info:VehicleHover|null){
 const el=$('#vehicle-hotspot');clearTimeout(vehicleHoverTimer);
 if(!info){vehicleHoverTimer=setTimeout(()=>{if(!el.matches(':hover'))el.classList.add('hidden');},500);return;}
 if(driving)return;hoveredVehicle=info.id;el.classList.remove('hidden');el.style.left=`${clamp(info.screenX,80,innerWidth-90)}px`;el.style.top=`${clamp(info.screenY-24,130,innerHeight-205)}px`;
}
function updateDriveHud(info:DrivingStatus){
 driving=info.active;document.body.classList.toggle('driving',driving);$('#drive-hud').classList.toggle('hidden',!driving);$('#drive-speed').innerHTML=`${fmt(Math.abs(info.speed))} <small>km/h</small>`;$('#drive-status').textContent=info.blocked??[info.drifting?'Drift':info.label,info.speedLimit?`Tempo ${fmt(info.speedLimit)}`:''].filter(Boolean).join(' · ');$('#drive-status').classList.toggle('drive-warning',!!info.blocked);$('#drive-hud').classList.toggle('is-drifting',!!info.drifting);if(driving){$('#vehicle-hotspot').classList.add('hidden');$('#build-preview').classList.add('hidden');$('#inspector').classList.add('hidden');}
}
function renderDayClock(){const hour=scene?scene.getTimeOfDay():state.settings.timeOfDay;$('#day-clock').textContent=`${String(Math.floor(hour)).padStart(2,'0')}:${String(Math.floor(hour%1*60)).padStart(2,'0')}`;night=hour<6||hour>=19;const button=$('#night-btn');if(button.getAttribute('aria-pressed')!==String(night)){button.setAttribute('aria-pressed',String(night));button.classList.toggle('active',night);button.innerHTML=icon(night?'moon':'sun');refreshIcons(button);}}
function setBuildingLights(enabled:boolean){state.settings.buildingLights=enabled;scene.setBuildingLights(enabled);renderLightSwitch();clearUndo();scheduleSave();}
function renderLightSwitch(){const button=$('#building-lights-btn');button.classList.toggle('active',state.settings.buildingLights);button.setAttribute('aria-pressed',String(state.settings.buildingLights));button.title=state.settings.buildingLights?'Stadtbeleuchtung ausschalten (L)':'Stadtbeleuchtung einschalten (L)';button.innerHTML=icon(state.settings.buildingLights?'lightbulb':'lightbulb-off');refreshIcons(button);}
function setOverlay(v:Overlay){overlay=v;scene.setOverlay(v);drawMinimap();const legend=$('#overlay-legend');if(v==='none'){legend.classList.add('hidden');return;}const labels:Record<string,string[]>={power:['Stromversorgung','Ohne Strom','Versorgt'],water:['Wasserversorgung','Ohne Wasser','Versorgt'],landvalue:['Grundstückswert','Niedrig','Hoch'],pollution:['Umweltbelastung','Sauber','Belastet'],traffic:['Verkehrsdichte','Freie Fahrt','Stau'],terrain:['Geländehöhen','Meereshöhe','Hochland']};const [title,a,b]=labels[v];legend.innerHTML=`<strong>${title}</strong><div class="legend-gradient ${v}"></div><div><span>${a}</span><span>${b}</span></div>`;legend.classList.remove('hidden');}
function openModal(type:string){modal=type;renderModal();}
function closeModal(){modal='';$('#modal-root').innerHTML='';}
function modalShell(title:string,kicker:string,body:string,wide=false){$('#modal-root').innerHTML=`<div class="modal-backdrop"><section class="modal ${wide?'wide':''}" role="dialog" aria-modal="true" aria-label="${title}"><header class="modal-header"><div><span class="eyebrow">${kicker}</span><h2>${title}</h2></div><button class="icon-btn close-modal" title="Schließen">${icon('x')}</button></header>${body}</section></div>`;$('.close-modal').onclick=closeModal;$('.modal-backdrop').onclick=e=>{if(e.target===$('.modal-backdrop'))closeModal();};refreshIcons($('#modal-root'));$('.close-modal').focus();}
function renderModal(){
 if(modal==='progression'){modalShell('Deine Stadt hat große Pläne.','AUFTRÄGE · AUSBAUSTUFEN · STADTZIEL',renderProgressionDialog(state,progressionTab),true);progressionBindings($('#modal-root'));
 } else if(modal==='camera'){modalShell('Deine Stadt aus jedem Blickwinkel.','KAMERA & BAUEN',`<div class="camera-guide">${[['hand','M · Bewegen','Wähle die Hand oder drücke M. Dann mit der linken Maustaste ziehen. Alternativ: mittlere Maustaste oder Alt + links.'],['move','W A S D · Navigieren','Bewege die Kamera über die Region. Die Pfeiltasten funktionieren ebenfalls.'],['rotate-cw','Rechts ziehen · Drehen','Rechte Maustaste gedrückt halten. Q und E drehen in festen Schritten.'],['zoom-in','Mausrad · Zoomen','Scrolle zum Vergrößern und Verkleinern. Die Minikarte bringt dich direkt an einen Ort.'],['globe','Region · Überblick','Die Weltkugel zeigt die ganze Region. Das Fadenkreuz bringt dich zur Innenstadt.'],['rotate-cw','R · Gebäude drehen','Wähle ein großes Gebäude und drehe seine komplette Baufläche mit R.'],['car','Selbst fahren','Zeige auf ein Fahrzeug und klicke auf das Lenkrad. W/S beschleunigt und bremst, A/D lenkt; Esc steigt aus.'],['rotate-ccw','Handbremse · Driften','Halte bei etwas Tempo die Leertaste und lenke. Beim Loslassen finden die Reifen wieder Halt.'],['lightbulb','L · Stadtbeleuchtung','Schalte Fenster und versorgte Straßenlaternen über die Glühbirne oder Taste L.'],['person-standing','C · Bewohner greifen','Greife eine Figur und hebe sie mit der Maus an. Sanft absetzen lässt sie weiterlaufen; ein kräftiger Wurf kann sie töten.']].map(([ic,title,desc])=>`<article>${icon(ic)}<div><h3>${title}</h3><p>${desc}</p></div></article>`).join('')}</div><button id="camera-use-pan" class="button primary full">${icon('hand')} Kamera jetzt bewegen</button>`,true);$('#camera-use-pan').onclick=()=>{closeModal();selectTool('pan');};
 } else if(modal==='budget'){
 const s=state.stats;
 modalShell('Ein guter Plan für morgen.','STADTHAUSHALT',`<div class="budget-overview"><div><small>Verfügbare Mittel</small><strong>${euro(state.money)}</strong></div><span class="budget-balance ${s.balance<0?'negative':''}">${s.balance>=0?'+':''}${euro(s.balance)}<small>pro Monat</small></span></div><div class="budget-columns"><div class="budget-card"><h3>Monatliche Bilanz</h3><div><span>Steuern & Wirtschaft</span><b class="positive">+ ${euro(s.income)}</b></div><div><span>Betrieb & Stadtversorgung</span><b>− ${euro(s.expenses)}</b></div><div class="total"><span>Überschuss</span><b>${euro(s.balance)}</b></div></div><div class="budget-card"><h3>Steuersatz</h3><div class="slider-label"><span>Einwohner & Unternehmen</span><b id="tax-value">${state.tax} %</b></div><input id="tax-slider" type="range" min="0" max="25" step="1" value="${state.tax}" aria-label="Steuersatz"/><p>Niedrige Steuern fördern Zuzug. Hohe Steuern erhöhen Einnahmen, senken aber die Zufriedenheit.</p></div></div><h3 class="funding-title">Investiere in Lebensqualität</h3><div class="funding-grid">${([['police','shield-check','Polizei'],['fire','flame','Feuerwehr'],['health','heart-pulse','Gesundheit'],['education','graduation-cap','Bildung']] as const).map(([key,ic,label])=>`<div class="funding-item"><label for="funding-${key}">${icon(ic)} ${label}<b id="funding-${key}-value">${state.funding[key]} %</b></label><input type="range" id="funding-${key}" data-funding="${key}" min="0" max="150" step="10" value="${state.funding[key]}"/></div>`).join('')}</div><div class="loan-row"><div><strong>Stadtanleihe</strong><small>Offene Kredite: ${euro(state.loan)} · Zinsen im Monatsbudget</small></div><button class="button secondary" id="repay-loan" ${state.loan<=0?'disabled':''}>10.000 € zurückzahlen</button><button class="button primary" id="take-loan">10.000 € aufnehmen</button></div>`,true);
 $('#tax-slider').oninput=e=>{state.tax=Number((e.target as HTMLInputElement).value);$('#tax-value').textContent=`${state.tax} %`;recalculate(state);clearUndo();renderStats();scheduleSave();};$('#tax-slider').onchange=()=>rerenderKeepingFocus('tax-slider');document.querySelectorAll<HTMLInputElement>('[data-funding]').forEach(el=>{el.oninput=()=>{const key=el.dataset.funding as keyof CityState['funding'];state.funding[key]=Number(el.value);$(`#funding-${key}-value`).textContent=`${el.value} %`;recalculate(state);clearUndo();renderStats();scheduleSave();};el.onchange=()=>rerenderKeepingFocus(el.id);});$('#take-loan').onclick=()=>{const r=takeLoan(state);if(r.ok)cityChanged();toast(r.message,r.ok?'good':'warning');renderStats();renderModal();};$('#repay-loan').onclick=()=>{const r=repayLoan(state);if(r.ok)cityChanged();toast(r.message,r.ok?'good':'warning');renderStats();renderModal();};
 } else if(modal==='reports'){
 const s=state.stats;modalShell('So geht es deiner Stadt.','STADTBERICHT',`<div class="report-grid">${[['users','Einwohner',fmt(s.population)],['briefcase-business','Arbeitsplätze',fmt(s.jobs)],['smile','Zufriedenheit',`${fmt(s.happiness)} %`],['leaf','Umweltbelastung',`${fmt(s.pollution)} %`]].map(([ic,label,v])=>`<div class="report-metric">${icon(ic)}<small>${label}</small><strong>${v}</strong></div>`).join('')}</div><div class="chart-header"><h3>Bevölkerungsentwicklung</h3><span>Die letzten ${Math.min(36,state.history.length)} Monate</span></div><div class="population-chart">${historyChart()}</div><div class="service-grid">${[['zap','Strom',s.powerDemand,s.powerSupply,'Einh.'],['droplets','Wasser',s.waterDemand,s.waterSupply,'Einh.']].map(([ic,label,demand,supply,unit])=>`<div class="service-capacity"><div>${icon(String(ic))}<b>${label}</b><span>${fmt(Number(demand))} / ${fmt(Number(supply))} ${unit}</span></div><div class="progress-track"><div style="width:${clamp(Number(demand)/Math.max(1,Number(supply))*100,0,100)}%;background:${Number(demand)>Number(supply)?'#d88162':'#74a695'}"></div></div></div>`).join('')}</div><div class="quality-grid">${[['Bildung',s.education],['Gesundheit',s.health],['Sicherheit',s.safety],['Verkehrsdichte',s.traffic]].map(([label,value])=>`<div><span>${label}</span><b>${fmt(Number(value))} %</b></div>`).join('')}</div><p class="modal-note">Versorgte Bauzonen wachsen mit der Nachfrage. Parks und Stadtdienste erhöhen die Lebensqualität; Industrie kann Nachbargrundstücke belasten.</p>`,true);
 } else if(modal==='news'){
 modalShell('Geschichten aus deiner Stadt.','STADTJOURNAL',`<div class="event-list">${state.events.length?state.events.map(e=>`<article class="event ${e.type}"><span class="event-icon">${icon(e.type==='good'?'sprout':e.type==='warning'?'triangle-alert':'newspaper')}</span><div><small>${MONTHS[e.month%12]} ${2000+Math.floor(e.month/12)}</small><h3>${escape(e.title)}</h3><p>${escape(e.message)}</p></div></article>`).join(''):'<p>Die erste Seite deiner Stadtgeschichte ist noch leer.</p>'}</div>`);
 } else if(modal==='help'){
 modalShell('Eine Stadt nach deinen Ideen.','WILLKOMMEN IN NEUSTADT',`<div class="help-cover"><img src="${import.meta.env.BASE_URL}assets/neustadt-cover.png" alt="Originales 3D-Stadtmotiv von Neustadt"/><div><span>DEIN KLEINES STÜCK ZUKUNFT</span><h3>Baue. Verbinde.<br>Lass es wachsen.</h3></div></div><div class="help-steps">${[['01','route','Verbinde deine Stadt','Ziehe Straßen über das Land. Große Gebäude benötigen ihre gesamte Baufläche; mit R kannst du sie drehen. Zonen brauchen einen Straßenanschluss, damit Menschen einziehen und Unternehmen entstehen.'],['02','house','Gib Ideen einen Platz','Baue Wohn-, Gewerbe- und Industriezonen. Achte auf die Nachfrage; neue Gebäude entstehen von selbst und entwickeln sich weiter.'],['03','zap','Sorge für das Wesentliche','Verbinde Kraftwerke über Stromleitungen und Wasserwerke über unterirdische Rohre mit deinen Baugebieten. Schulen, Kliniken, Polizei und Parks machen die Stadt lebenswert.'],['04','chart-no-axes-combined','Denke einen Schritt weiter','Erfülle Aufträge, hole Belohnungen ab und entwickle deine Kleinstadt über die Großstadt zur Metropole. Im Stadtziel wartet eine lebenswerte Stadt für 25.000 Menschen.']].map(([num,ic,title,desc])=>`<article><span>${num}</span><div><h3>${icon(ic)} ${title}</h3><p>${desc}</p></div></article>`).join('')}</div><div class="keyboard-help"><span><kbd>Leertaste</kbd> Pause</span><span><kbd>1–5</kbd> Bauen</span><span><kbd>B</kbd> Abreißen</span><span><kbd>Q / E</kbd> Drehen</span><span><kbd>G</kbd> Raster</span><span><kbd>Strg Z</kbd> Rückgängig</span></div><button class="button primary full" id="start-playing">Meine Stadt gestalten ${icon('arrow-right')}</button>`,true);$('#start-playing').onclick=closeModal;
 } else if(modal==='graphics'){
 modalShell('Deine Stadt im besten Licht.','GRAFIK & BELEUCHTUNG',`<div class="weather-options"><div><h3>Wetter & Oberflächen</h3><p>Regen erzeugt nasse Straßen und Pfützen.</p></div><button class="button ${state.settings.weather==='clear'?'primary':'secondary'}" data-weather="clear">${icon('sun')} Klar</button><button class="button ${state.settings.weather==='rain'?'primary':'secondary'}" data-weather="rain">${icon('cloud-rain')} Regen</button></div><div class="daylight-settings"><label for="building-lights">Gebäude- und Straßenbeleuchtung<input id="building-lights" type="checkbox" ${state.settings.buildingLights?'checked':''}/></label><small>Fenster, Laternen und ihre Lichtflächen einschalten. Auch direkt oben mit der Glühbirne oder Taste L.</small><label for="day-cycle">Automatischer Tag-Nacht-Wechsel<input id="day-cycle" type="checkbox" ${state.settings.dayNightCycle?'checked':''}/></label><small>Ein Tag dauert etwa vier Minuten bei laufender Stadt. Sonne und Schatten folgen der Uhrzeit.</small><label for="day-hour">Tageszeit <b id="day-hour-value">${Math.floor(state.settings.timeOfDay)}:00</b></label><input id="day-hour" type="range" min="0" max="23" step="1" value="${Math.floor(state.settings.timeOfDay)}"/></div><p class="modal-note">Wähle Auflösung, Schattendetails und Kantenglättung für deinen Rechner.</p><div class="graphics-presets">${([['performance','Flüssig','Reduzierte Auflösung und kompakte Schatten'],['balanced','Ausgewogen','Weiche Schatten und geglättete Kanten'],['ultra','Sehr hoch','Hohe Auflösung und feinere Schattendetails']] as const).map(([id,label,desc])=>`<button class="graphics-preset ${quality===id?'active':''}" data-quality="${id}">${icon(id==='performance'?'gauge':id==='balanced'?'sun':'sparkles')}<strong>${label}</strong><small>${desc}</small></button>`).join('')}</div>`);
 document.querySelectorAll<HTMLButtonElement>('[data-quality]').forEach(b=>b.onclick=()=>{quality=b.dataset.quality as typeof quality;scene.setGraphicsQuality(quality);safePreferenceSet('neustadt-quality',quality);renderModal();});$('#building-lights').onchange=e=>setBuildingLights((e.target as HTMLInputElement).checked);$('#day-cycle').onchange=e=>{state.settings.dayNightCycle=(e.target as HTMLInputElement).checked;scene.setDayNightCycle(state.settings.dayNightCycle);clearUndo();scheduleSave();};$('#day-hour').oninput=e=>{const hour=Number((e.target as HTMLInputElement).value);state.settings.timeOfDay=hour;state.settings.dayNightCycle=false;scene.setTimeOfDay(hour);scene.setDayNightCycle(false);$<HTMLInputElement>('#day-cycle').checked=false;$('#day-hour-value').textContent=`${hour}:00`;clearUndo();scheduleSave();};document.querySelectorAll<HTMLButtonElement>('[data-weather]').forEach(b=>b.onclick=()=>{state.settings.weather=b.dataset.weather as Weather;scene.setWeather(state.settings.weather);cityChanged();renderModal();});
 } else if(modal==='newcity'){
 modalShell('Alles beginnt mit einer Idee.','NEUE STADT',`<p class="modal-note">Deine aktuelle Stadt bleibt erhalten, wenn du sie vorher exportierst. Beim Start wird der automatische Spielstand durch die neue Stadt ersetzt.</p><label class="form-label">Name der Stadt<input id="new-name" type="text" maxlength="40" value="Lindenbucht"/></label><label class="form-label">Größe der Region<select id="new-size"><option value="64">64 × 64 · Kompakt</option><option value="96">96 × 96 · Weitläufig</option><option value="128" selected>128 × 128 · Große Region (10× bisherige Fläche)</option></select></label><label class="form-label">Landschafts-Seed<input id="new-seed" type="number" min="1" max="999999" value="${Math.floor(Math.random()*99999)+1}"/></label><div class="new-city-options"><button id="new-starter" class="button primary">${icon('building-2')} Mit Starterstadt beginnen</button><button id="new-empty" class="button secondary">${icon('sprout')} Auf freiem Land beginnen</button></div>`);const start=(empty:boolean)=>{const seed=clamp(Number($<HTMLInputElement>('#new-seed').value)||7341,1,999999);const name=$<HTMLInputElement>('#new-name').value.trim().slice(0,40)||'Lindenbucht';state=createCity(seed,empty,Number($<HTMLSelectElement>('#new-size').value));state.name=name;saveBlocked=false;recoveryRaw=null;undoStack=[];selected=null;lastRank=getRank(state).id;victoryAnnounced=state.progression.victory;tickAccumulator=0;scene.exitDrive();syncScene(true);renderStats();renderTools();$('#inspector').classList.add('hidden');closeModal();save(false);toast(`Willkommen in ${name}. Deine Geschichte beginnt.`,'good');};$('#new-starter').onclick=()=>start(false);$('#new-empty').onclick=()=>start(true);
 } else if(modal==='disaster'){
 modalShell('Wenn die Stadt dich braucht.','EXPERIMENTIERMODUS & KATASTROPHEN',`<label class="disaster-switch"><span><strong>Katastrophenwerkzeuge aktivieren</strong><small>Experimentiermodus: Ereignisse absichtlich auslösen.</small></span><input id="disaster-enabled" type="checkbox" ${state.settings.disastersEnabled?'checked':''}/></label><p class="modal-note">Diese Ereignisse beschädigen Gebäude und können Strom- und Wassernetze unterbrechen. Ein Rückgängig ist bis zum nächsten Spielmonat möglich.</p><div class="disaster-grid">${([['fire','flame','Großbrand','Feuer breitet sich aus. Versorgte Feuerwehren helfen.'],['earthquake','activity','Erdbeben','Gebäude und Straßen können einstürzen.'],['flood','waves','Hochwasser','Tiefliegende Küstenflächen und Anlagen werden beschädigt.'],['storm','wind','Schwerer Sturm','Windschäden treffen Gebäude und Stromleitungen.']] as const).map(([id,ic,title,desc])=>`<button data-disaster="${id}" ${!state.settings.disastersEnabled?'disabled':''}>${icon(ic)}<strong>${title}</strong><span>${desc}</span></button>`).join('')}</div>`);
 $('#disaster-enabled').onchange=e=>{state.settings.disastersEnabled=(e.target as HTMLInputElement).checked;cityChanged();renderModal();};document.querySelectorAll<HTMLButtonElement>('[data-disaster]').forEach(b=>b.onclick=()=>{snapshot();const result=triggerDisaster(state,b.dataset.disaster as DisasterKind);if(!result.ok){undoStack.pop();return toast(result.message,'warning');}syncScene();renderStats();scheduleSave();closeModal();toast(result.message,'warning');});
 } else {
 modalShell('Deine Stadt. Dein Spiel.','STADTMENÜ',` ${recoveryRaw?'<div class="storage-warning">Der nicht lesbare Originalspielstand wird nicht überschrieben. <button id="download-recovery" class="text-link">Originaldatei sichern</button></div>':''}<div class="menu-city"><img src="${import.meta.env.BASE_URL}assets/neustadt-cover.png" alt="Neustadt Küstenstadt"/><div><strong>${escape(state.name)}</strong><span>${fmt(state.stats.population)} Einwohner · ${MONTHS[state.month%12]} ${2000+Math.floor(state.month/12)}</span></div></div><label class="form-label">Stadtname<div class="rename-row"><input id="rename-input" value="${escape(state.name)}" maxlength="40"/><button class="button secondary" id="rename-btn">Ändern</button></div></label><div class="menu-grid">${[['menu-save','save','Stadt speichern','Lokal in diesem Browser'],['menu-export','download','Spielstand exportieren','Als JSON-Datei sichern'],['menu-import','upload','Spielstand importieren','Gesicherte Stadt fortsetzen'],['menu-new','sprout','Neue Stadt','Eine neue Geschichte beginnen'],['menu-photo','camera','Stadt fotografieren','Deine Perspektive als PNG'],['menu-disaster','flame','Katastrophen','Experimentiermodus aktivieren'],['menu-progress','flag','Stadtentwicklung','3 Stufen · Aufträge · Challenges'],['menu-camera','hand','Kamera & Bewohner','Navigation und Greifen']].map(([id,ic,title,sub])=>`<button id="${id}">${icon(ic)}<span><strong>${title}</strong><small>${sub}</small></span>${icon('chevron-right')}</button>`).join('')}</div><div class="menu-footer"><span>NEUSTADT · REGIONEN & STADTLEBEN · V2</span><button id="menu-help" class="text-link">Spielanleitung ${icon('arrow-up-right')}</button></div>`);
 $('#download-recovery')?.addEventListener('click',()=>{if(recoveryRaw)download(new Blob([recoveryRaw],{type:'application/json'}),'neustadt-original-sicherung.json');});$('#rename-btn').onclick=()=>{const name=$<HTMLInputElement>('#rename-input').value.trim();if(name){state.name=name;cityChanged();save(false);toast('Deine Stadt hat einen neuen Namen.','good');renderModal();}};$('#menu-save').onclick=()=>save();$('#menu-export').onclick=()=>download(new Blob([serializeCity(state)],{type:'application/json'}),`${state.name.toLowerCase().replace(/[^a-z0-9äöüß_-]/g,'-')}-spielstand.json`);$('#menu-import').onclick=()=>{$<HTMLInputElement>('#import-file').click();};$('#menu-new').onclick=()=>openModal('newcity');$('#menu-photo').onclick=()=>{const a=document.createElement('a');a.href=scene.screenshot();a.download='neustadt-stadtansicht.png';a.click();toast('Deine Stadtansicht wurde als PNG exportiert.','good');};$('#menu-disaster').onclick=()=>openModal('disaster');$('#menu-help').onclick=()=>openModal('help');$('#menu-progress').onclick=()=>openModal('progression');$('#menu-camera').onclick=()=>openModal('camera');
 }
}
function historyChart(){const points=state.history.slice(-36);if(points.length<2)return '<div class="chart-empty">Die erste Statistik entsteht, sobald ein Spielmonat vergangen ist.</div>';const max=Math.max(...points.map(p=>p.population),1)*1.15;const w=660,h=150,pad=30;const coords=points.map((p,i)=>`${pad+i*(w-pad*2)/(points.length-1)},${h-pad-p.population/max*(h-pad*2)}`);return `<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Bevölkerungsentwicklung von ${fmt(points[0].population)} auf ${fmt(points.at(-1)!.population)} Einwohner"><defs><linearGradient id="chart-fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stop-color="#7fac97" stop-opacity=".35"/><stop offset="100%" stop-color="#7fac97" stop-opacity="0"/></linearGradient></defs>${[.25,.5,.75].map(v=>`<line x1="${pad}" y1="${h-pad-v*(h-pad*2)}" x2="${w-pad}" y2="${h-pad-v*(h-pad*2)}" stroke="#e7eae2" stroke-dasharray="3 5"/>`).join('')}<path d="M ${pad},${h-pad} L ${coords.join(' L ')} L ${w-pad},${h-pad} Z" fill="url(#chart-fill)"/><polyline points="${coords.join(' ')}" fill="none" stroke="#55856f" stroke-width="2.5" stroke-linejoin="round"/><text x="${pad}" y="${h-4}" fill="#8a958b" font-size="10">${MONTHS[points[0].month%12]} ${2000+Math.floor(points[0].month/12)}</text><text x="${w-pad}" y="${h-4}" text-anchor="end" fill="#8a958b" font-size="10">${MONTHS[points.at(-1)!.month%12]} ${2000+Math.floor(points.at(-1)!.month/12)}</text></svg>`;}
function rerenderKeepingFocus(id:string){const value=$<HTMLInputElement>('#'+id)?.value;renderModal();const el=$<HTMLInputElement>('#'+id);if(el){if(value!==undefined)el.value=value;el.focus();}}

function download(blob:Blob,name:string){const a=document.createElement('a'),url=URL.createObjectURL(blob);a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Spielstand exportiert.','good');}
function wireEvents(){
 document.querySelectorAll<HTMLButtonElement>('[data-category]').forEach(b=>b.onclick=()=>{category=b.dataset.category!;document.querySelectorAll('[data-category]').forEach(x=>x.classList.toggle('active',x===b));renderTools();});
 document.querySelectorAll<HTMLButtonElement>('[data-speed]').forEach(b=>b.onclick=()=>{state.speed=Number(b.dataset.speed) as CityState['speed'];renderStats();});document.querySelectorAll<HTMLButtonElement>('[data-brush]').forEach(b=>b.onclick=()=>{brush=Number(b.dataset.brush);scene.setTool(tool,brush,buildingRotation);document.querySelectorAll('[data-brush]').forEach(x=>x.classList.toggle('active',x===b));});
 $('#vehicle-hotspot').onmouseleave=()=>{$('#vehicle-hotspot').classList.add('hidden');};$('#vehicle-hotspot').onclick=()=>{if(hoveredVehicle!==null&&scene.enterDrive(hoveredVehicle)){$('#vehicle-hotspot').classList.add('hidden');}};$('#exit-drive').onclick=()=>scene.exitDrive();$('#goals-btn').onclick=()=>openModal('progression');$('#overview-btn').onclick=()=>scene.overview();$('#pan-btn').onclick=()=>selectTool('pan');$('#camera-help').onclick=()=>openModal('camera');$('#rotate-building').onclick=()=>{buildingRotation=((buildingRotation+1)%4) as 0|1|2|3;scene.setTool(tool,brush,buildingRotation);};$('#graphics-btn').onclick=()=>openModal('graphics');$('#save-btn').onclick=()=>save();$('#undo-btn').onclick=undo;$('#menu-btn').onclick=()=>openModal('menu');$('#city-name').onclick=()=>openModal('menu');$('#budget-stat').onclick=()=>openModal('budget');$('#population-stat').onclick=()=>openModal('reports');$('#happiness-stat').onclick=()=>openModal('reports');$('#help-btn')?.addEventListener('click',()=>openModal('help'));$('#help-shortcut').onclick=()=>openModal('help');$('#brand-help').onclick=e=>{e.preventDefault();openModal('help');};$('#news-btn').onclick=()=>openModal('news');$('#advisor-close')?.addEventListener('click',()=>{minimizeAdvisor=true;$('#advisor').classList.add('hidden');});
 $('#building-lights-btn').onclick=()=>setBuildingLights(!state.settings.buildingLights);$('#zoom-in').onclick=()=>scene.zoom(1);$('#zoom-out').onclick=()=>scene.zoom(-1);$('#rotate-left').onclick=()=>scene.rotate(-1);$('#rotate-right').onclick=()=>scene.rotate(1);$('#camera-home').onclick=()=>scene.resetCamera();$('#overlay-select').onchange=e=>setOverlay((e.target as HTMLSelectElement).value as Overlay);$('#grid-btn').onclick=()=>{grid=!grid;scene.setGrid(grid);$('#grid-btn').classList.toggle('active',grid);$('#grid-btn').setAttribute('aria-pressed',String(grid));};$('#night-btn').onclick=()=>{night=scene.getTimeOfDay()>=6&&scene.getTimeOfDay()<19;state.settings.timeOfDay=night?21:14;state.settings.dayNightCycle=false;scene.setTimeOfDay(state.settings.timeOfDay);scene.setDayNightCycle(false);$('#night-btn').innerHTML=icon(night?'moon':'sun');$('#night-btn').classList.toggle('active',night);$('#night-btn').setAttribute('aria-pressed',String(night));refreshIcons($('#night-btn'));clearUndo();scheduleSave();};
 $('#minimap').onclick=e=>{const rect=$('#minimap').getBoundingClientRect();scene.focus(Math.floor((e.clientX-rect.left)/rect.width*state.size),Math.floor((e.clientY-rect.top)/rect.height*state.size));};
 $('#import-file').onchange=async e=>{const file=(e.target as HTMLInputElement).files?.[0];if(!file)return;try{if(file.size>12_000_000)throw Error('Datei ist zu groß.');const imported=deserializeCity(await file.text());state=imported.size===40?expandCity(imported,128):imported;state.speed=0;saveBlocked=false;recoveryRaw=null;undoStack=[];selected=null;lastRank=getRank(state).id;victoryAnnounced=state.progression.victory;tickAccumulator=0;scene.exitDrive();syncScene(true);renderStats();renderTools();$('#inspector').classList.add('hidden');closeModal();save(false);toast(`${state.name} erfolgreich geladen.`,'good');}catch(err){toast(`Spielstand konnte nicht geladen werden: ${err instanceof Error?err.message:'Ungültige Datei'}`,'warning');}(e.target as HTMLInputElement).value='';};
 window.addEventListener('keydown',e=>{if(modal&&e.key==='Tab'){const focusable=[...document.querySelectorAll<HTMLElement>('.modal button:not([disabled]),.modal input,.modal select,.modal a[href]')];const current=focusable.indexOf(document.activeElement as HTMLElement);if(e.shiftKey&&current<=0){e.preventDefault();focusable.at(-1)?.focus();}else if(!e.shiftKey&&current===focusable.length-1){e.preventDefault();focusable[0]?.focus();}}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();save();return;}if(e.key==='Escape'){if(driving){scene.exitDrive();return;}if(modal)closeModal();else{selectTool('inspect');$('#inspector').classList.add('hidden');}return;}if((e.target as HTMLElement).matches('input,select,textarea')||modal||driving)return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return;}if(e.code==='Space'){e.preventDefault();state.speed=state.speed?0:1;renderStats();}if(e.key.toLowerCase()==='r'&&TOOL_DEFS[tool]?.footprint){e.preventDefault();$('#rotate-building').click();}const keys:Record<string,Tool>={'m':'pan','c':'citizen','1':'road','2':'residential','3':'commercial','4':'industrial','5':'park','b':'bulldoze','v':'inspect'};if(keys[e.key.toLowerCase()]){category='favorites';document.querySelectorAll<HTMLElement>('[data-category]').forEach(b=>b.classList.toggle('active',b.dataset.category===category));selectTool(keys[e.key.toLowerCase()]);}if(e.key.toLowerCase()==='q')scene.rotate(-1);if(e.key.toLowerCase()==='e')scene.rotate(1);if(e.key.toLowerCase()==='g')$('#grid-btn').click();if(e.key.toLowerCase()==='n')$('#night-btn').click();if(e.key.toLowerCase()==='l')$('#building-lights-btn').click();if(e.key.toLowerCase()==='h')openModal('help');});
 window.addEventListener('beforeunload',()=>save(false));document.addEventListener('visibilitychange',()=>{if(document.hidden)save(false);previousTime=performance.now();});
}
function loop(time:number){const delta=Math.min((time-previousTime)/1000,.25);previousTime=time;fps=1/Math.max(.001,delta);frameCount++;if(!document.hidden&&!modal&&state.speed>0){tickAccumulator+=delta*[0,1,2,3][state.speed];if(tickAccumulator>=5){tickAccumulator-=5;clearUndo();tick(state);syncScene();renderStats();renderInspector();const rank=getRank(state);if(rank.id>lastRank){lastRank=rank.id;renderTools();toast(`Ausbaustufe ${rank.id+1}: ${rank.name}! Neue Gebäude sind freigeschaltet.`,'good');}if(state.progression.victory&&!victoryAnnounced){victoryAnnounced=true;progressionTab='goal';openModal('progression');}if(state.events[0]?.id!==lastEvent){lastEvent=state.events[0]?.id??0;const latest=state.events[0];if(latest?.type==='warning')toast(latest.message,'warning');}}}if(frameCount%30===0&&scene)renderDayClock();if(!savePending&&Date.now()>nextAutosave)void save(false);requestAnimationFrame(loop);}
async function start(){
 try{
  const load=await loadSavedCity();
  if(load.error){loadError=load.error;saveBlocked=true;}
  if(load.raw){try{const city=deserializeCity(load.raw);if(load.source==='legacy'){try{await backupLegacy(load.raw);}catch{loadNotice='Die alte Sicherung bleibt erhalten. Die Stadt wird geladen.';}}state=city.size===40?expandCity(city,128):city;state.speed=0;saved=true;if(city.size===40)loadNotice=`${state.name} wurde mit deiner bestehenden Bebauung auf ${state.size} × ${state.size} Felder erweitert.`;}catch(error){saveBlocked=true;recoveryRaw=load.raw;loadError=`Der bisherige Spielstand bleibt geschützt: ${error instanceof Error?error.message:'Laden fehlgeschlagen'}`;}}
  const preference=safePreferenceGet('neustadt-quality');if(['performance','balanced','ultra'].includes(preference??''))quality=preference as typeof quality;
  lastRank=getRank(state).id;victoryAnnounced=state.progression.victory;syncScene();renderTools();renderStats();wireEvents();refreshIcons();$('#loading-screen').classList.add('loaded');setTimeout(()=>$('#loading-screen').remove(),650);
  if(saveBlocked)$('#autosave-status').textContent='Alter Spielstand geschützt · Export möglich';if(loadError)toast(loadError,'warning');else if(loadNotice)toast(loadNotice,'good');else if(saved)toast('Willkommen zurück. Deine Stadt wurde geladen.','good');
  if(!saveBlocked)scheduleSave();requestAnimationFrame(loop);
  Object.defineProperty(window,'neustadtDebug',{get:()=>({state:structuredClone(state),tool,overlay,night,grid,quality,driving,rotation:buildingRotation,renderStatus:{mode:"realtime",status:"Echtzeit"},preview:lastPreview,interactionTargets:scene.getInteractionTargets?.(),diagnostics:scene.getDiagnostics?.(),drivingStatus:scene.getDrivingStatus(),fps:Math.round(fps),frames:frameCount,buildCount,undoCount:undoStack.length,saveBlocked,savePending,saveFailed})});
 }catch(error){$('#loading-screen').innerHTML=`<h2>Die Stadt konnte nicht gestartet werden.</h2><p>${escape(error instanceof Error?error.message:'Unbekannter Fehler')}</p><p>Bitte verwende einen Browser mit aktivierter WebGL-Grafik.</p>`;console.error(error);}
}
start();
